Repository GSM-MSG/SMS-iOS, pull requests merged in 2023-06, with the labels that each got.

#156 🔀 :: JwtInterceptor에 Jwt 토큰 자동 담기 및 쿠키 제거
  Projects/Domain/BaseDomain/Sources/Interceptors/Jwt/JwtInterceptor.swift
  Projects/Domain/MajorDomain/Sources/Endpoint/MajorEndpoint.swift
  Projects/Feature/SigninFeature/Sources/Intent/SigninIntent.swift
  Tuist/Dependencies.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#161 🔀 :: 학생 리스트 UseCase 작성
  Projects/Domain/StudentDomain/Interface/DI/StudentDomainBuildable.swift
  Projects/Domain/StudentDomain/Interface/DTO/Request/FetchStudentListRequestDTO.swift
  Projects/Domain/StudentDomain/Interface/DataSource/RemoteStudentDataSource.swift
  Projects/Domain/StudentDomain/Interface/Entity/PagedStudentListEntity.swift
  Projects/Domain/StudentDomain/Interface/Entity/SingleStudentEntity.swift
  Projects/Domain/StudentDomain/Interface/Repository/StudentRepository.swift
  Projects/Domain/StudentDomain/Interface/UseCase/FetchStudentListUseCase.swift
  Projects/Domain/StudentDomain/Sources/DI/StudentDomainComponent.swift
  Projects/Domain/StudentDomain/Sources/DTO/Response/FetchStudentListResponseDTO.swift
  Projects/Domain/StudentDomain/Sources/DataSource/RemoteStudentDataSourceImpl.swift
  Projects/Domain/StudentDomain/Sources/Endpoint/StudentEndpoint.swift
  Projects/Domain/StudentDomain/Sources/Repository/StudentRepositoryImpl.swift
  Projects/Domain/StudentDomain/Sources/UseCase/FetchStudentListUseCaseImpl.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#163 🔀 :: 로그인 시 유저 권한 정보 저장
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/Dependency+Target.swift
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/ModulePaths.swift
  Projects/App/Project.swift
  Projects/App/Sources/Application/DI/AppComponent.swift
  Projects/App/Sources/Application/NeedleGenerated.swift
  Projects/Domain/AuthDomain/Interface/DataSource/RemoteAuthDataSource.swift
  Projects/Domain/AuthDomain/Interface/Entity/IsAlreadySignUp.swift
  Projects/Domain/AuthDomain/Interface/Entity/UserSignupInfoEntity.swift
  Projects/Domain/AuthDomain/Interface/Repository/AuthRepository.swift
  Projects/Domain/AuthDomain/Interface/UseCase/LoginUseCase.swift
  Projects/Domain/AuthDomain/Project.swift
  Projects/Domain/AuthDomain/Sources/DTO/Response/SigninResponseDTO.swift
  Projects/Domain/AuthDomain/Sources/DataSource/RemoteAuthDataSourceImpl.swift
  Projects/Domain/AuthDomain/Sources/Repository/AuthRepositoryImpl.swift
  Projects/Domain/AuthDomain/Sources/UseCase/LoginUseCaseImpl.swift
  Projects/Domain/AuthDomain/Testing/DataSource/RemoteAuthDataSourceSpy.swift
  Projects/Domain/AuthDomain/Testing/Repository/AuthRepositorySpy.swift
  Projects/Domain/AuthDomain/Testing/UseCase/LoginUseCaseSpy.swift
  Projects/Domain/UserDomain/Demo/Resources/LaunchScreen.storyboard
  Projects/Domain/UserDomain/Demo/Sources/AppDelegate.swift
  Projects/Domain/UserDomain/Interface/DI/UserDomainBuildable.swift
  Projects/Domain/UserDomain/Interface/DataSource/Local/LocalUserDataSource.swift
  Projects/Domain/UserDomain/Interface/Enum/UserRoleType.swift
  Projects/Domain/UserDomain/Interface/Repository/UserRepository.swift
  Projects/Domain/UserDomain/Interface/UseCase/LoadUserRoleUseCase.swift
  Projects/Domain/UserDomain/Interface/UseCase/SaveUserRoleUseCase.swift
  Projects/Domain/UserDomain/Project.swift
  Projects/Domain/UserDomain/Sources/DI/UserDomainComponent.swift
  Projects/Domain/UserDomain/Sources/DataSource/LocalUserDataSourceImpl.swift
  Projects/Domain/UserDomain/Sources/Repository/UserRepositoryImpl.swift
  Projects/Domain/UserDomain/Sources/UseCase/LoadUserRoleUseCaseImpl.swift
  Projects/Domain/UserDomain/Sources/UseCase/SaveUserRoleUseCaseImpl.swift
  Projects/Domain/UserDomain/Testing/Testing.swift
  Projects/Domain/UserDomain/Tests/UserDomainTest.swift
  Projects/Feature/InputInformationFeature/Project.swift
  Projects/Feature/SigninFeature/Project.swift
  Projects/Feature/SigninFeature/Sources/DI/SigninComponent.swift
  Projects/Feature/SigninFeature/Sources/Intent/SigninIntent.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#160 🔀 :: 세부스택 가져오는 페이지
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/Dependency+Target.swift
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/ModulePaths.swift
  Projects/App/Project.swift
  Projects/App/Sources/Application/DI/AppComponent.swift
  Projects/App/Sources/Application/NeedleGenerated.swift
  Projects/Core/DesignSystem/Resources/Icon/Icons.xcassets/Magnifyingglass.imageset/Contents.json
  Projects/Core/DesignSystem/Resources/Icon/Icons.xcassets/Magnifyingglass.imageset/magnifyingglass.svg
  Projects/Core/DesignSystem/Sources/Icon/SMSIcon.swift
  Projects/Core/DesignSystem/Sources/TextField/SMSIconTextField.swift
  Projects/Core/EventLimiter/Project.swift
  Projects/Core/EventLimiter/Sources/Debouncer.swift
  Projects/Core/EventLimiter/Sources/Throttler.swift
  Projects/Core/EventLimiter/Tests/DebouncerTest.swift
  Projects/Domain/BaseDomain/Sources/Base/SMSDomain.swift
  Projects/Domain/TechStackDomain/Interface/DI/TechStackDomainBuildable.swift
  Projects/Domain/TechStackDomain/Interface/DataSource/RemoteTechStackDataSource.swift
  Projects/Domain/TechStackDomain/Interface/Error/TechStackError.swift
  Projects/Domain/TechStackDomain/Interface/Repository/TechStackRepository.swift
  Projects/Domain/TechStackDomain/Interface/UseCase/FetchTechStackListUseCase.swift
  Projects/Domain/TechStackDomain/Project.swift
  Projects/Domain/TechStackDomain/Sources/DI/TechStackDomainComponent.swift
  Projects/Domain/TechStackDomain/Sources/DTO/Response/FetchTechStackListResponseDTO.swift
  Projects/Domain/TechStackDomain/Sources/DataSource/RemoteTechStackDataSourceImpl.swift
  Projects/Domain/TechStackDomain/Sources/Endpoint/TechStackEndpoint.swift
  Projects/Domain/TechStackDomain/Sources/Repository/TechStackRepositoryImpl.swift
  Projects/Domain/TechStackDomain/Sources/UseCase/FetchTechStackListUseCaseImpl.swift
  Projects/Domain/TechStackDomain/Testing/UseCase/FetchTechStackListUseCaseStub.swift
  Projects/Domain/TechStackDomain/Tests/TechStackDomainTest.swift
  Projects/Feature/TechStackAppendFeature/Demo/Resources/LaunchScreen.storyboard
  Projects/Feature/TechStackAppendFeature/Demo/Sources/DemoView.swift
  Projects/Feature/TechStackAppendFeature/Demo/Sources/TechStackAppendDemoApp.swift
  Projects/Feature/TechStackAppendFeature/Interface/TechStackAppendBuildable.swift
  Projects/Feature/TechStackAppendFeature/Project.swift
  Projects/Feature/TechStackAppendFeature/Sources/DI/TechStackAppendComponent.swift
  Projects/Feature/TechStackAppendFeature/Sources/Intent/TechStackAppendIntent.swift
  Projects/Feature/TechStackAppendFeature/Sources/Intent/TechStackAppendIntentProtocol.swift
  Projects/Feature/TechStackAppendFeature/Sources/Model/TechStackAppendModel.swift
  Projects/Feature/TechStackAppendFeature/Sources/Model/TechStackAppendModelProtocol.swift
  Projects/Feature/TechStackAppendFeature/Sources/Scene/TechStackAppendView.swift
  Projects/Feature/TechStackAppendFeature/Tests/TechStackAppendFeatureTest.swift
  Projects/Shared/ViewUtil/Sources/UtilView/HighlightedText.swift
  Tuist/Dependencies.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#166 🔀 :: GuestSignin 버튼 제작
  Projects/App/Sources/Application/NeedleGenerated.swift
  Projects/Feature/RootFeature/Sources/Intent/RootIntent.swift
  Projects/Feature/RootFeature/Sources/Model/RootModel.swift
  Projects/Feature/SigninFeature/Interface/SigninDelegate.swift
  Projects/Feature/SigninFeature/Sources/Intent/SigninIntent.swift
  Projects/Feature/SigninFeature/Sources/Intent/SigninIntentProtocol.swift
  Projects/Feature/SigninFeature/Sources/Scene/SigninView.swift
Labels: 0️⃣ Priority: Critical, ⚡️ Simple, ✨ Feature

#172 🔀 :: SMSLoading Modifier
  Projects/Core/DesignSystem/Sources/Loading/SMSLoading.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#170 🔀 :: 정보 입력 실패 시 유저에게 에러 메시지 전달
  Projects/Domain/StudentDomain/Interface/Error/StudentDomainError.swift
  Projects/Feature/InputInformationFeature/Sources/Intent/InputInformationIntent.swift
  Projects/Feature/InputInformationFeature/Sources/Intent/InputInformationIntentProtocol.swift
  Projects/Feature/InputInformationFeature/Sources/Model/InputInformationModel.swift
  Projects/Feature/InputInformationFeature/Sources/Model/InputInformationModelProtocol.swift
  Projects/Feature/InputInformationFeature/Sources/Scene/InputInformationView.swift
Labels: 2️⃣ Priority: Medium, ✨ Feature

#169 🔀 :: 학생 디테일 feature
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/Dependency+SPM.swift
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/Dependency+Target.swift
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/ModulePaths.swift
  Projects/App/Project.swift
  Projects/App/Sources/Application/DI/AppComponent.swift
  Projects/App/Sources/Application/NeedleGenerated.swift
  Projects/Core/DesignSystem/Resources/Icon/Icons.xcassets/Book.imageset/Contents.json
  Projects/Core/DesignSystem/Resources/Icon/Icons.xcassets/Book.imageset/book.svg
  Projects/Core/DesignSystem/Resources/Icon/Icons.xcassets/Profile.imageset/Profile.svg
  Projects/Core/DesignSystem/Sources/Font/Font+sms.swift
  Projects/Core/DesignSystem/Sources/Icon/SMSIcon.swift
  Projects/Core/DesignSystem/Sources/Loading/SMSLoading.swift
  Projects/Core/DesignSystem/Sources/Separator/SMSSeparator.swift
  Projects/Domain/BaseDomain/Sources/Base/BaseRetemoteDataSource.swift
  Projects/Domain/StudentDomain/Demo/Sources/DemoView.swift
  Projects/Domain/StudentDomain/Interface/DI/StudentDomainBuildable.swift
  Projects/Domain/StudentDomain/Interface/DataSource/RemoteStudentDataSource.swift
  Projects/Domain/StudentDomain/Interface/Entity/LanguageCertificateEntity.swift
  Projects/Domain/StudentDomain/Interface/Entity/StudentDetailEntity.swift
  Projects/Domain/StudentDomain/Interface/Enums/DepartmentType.swift
  Projects/Domain/StudentDomain/Interface/Enums/MilitaryServiceType.swift
  Projects/Domain/StudentDomain/Interface/Repository/StudentRepository.swift
  Projects/Domain/StudentDomain/Interface/Strategy/StudentDetailViewStrategy.swift
  Projects/Domain/StudentDomain/Interface/UseCase/FetchStudentDetailUseCase.swift
  Projects/Domain/StudentDomain/Sources/DI/StudentDomainComponent.swift
  Projects/Domain/StudentDomain/Sources/DTO/Response/FetchStudentDetailByGuestResponseDTO.swift
  Projects/Domain/StudentDomain/Sources/DTO/Response/FetchStudentDetailByStudentResponseDTO.swift
  Projects/Domain/StudentDomain/Sources/DTO/Response/FetchStudentDetailByTeacherResponseDTO.swift
  Projects/Domain/StudentDomain/Sources/DataSource/RemoteStudentDataSourceImpl.swift
  Projects/Domain/StudentDomain/Sources/Endpoint/StudentEndpoint.swift
  Projects/Domain/StudentDomain/Sources/Repository/StudentRepositoryImpl.swift
  Projects/Domain/StudentDomain/Sources/Strategy/StudentDetailByGuestStrategy.swift
  Projects/Domain/StudentDomain/Sources/Strategy/StudentDetailByStudentStrategy.swift
  Projects/Domain/StudentDomain/Sources/Strategy/StudentDetailByTeacherStrategy.swift
  Projects/Domain/StudentDomain/Sources/Strategy/StudentDetailStrategyExecutor.swift
  Projects/Domain/StudentDomain/Sources/UseCase/FetchStudentDetailUseCaseImpl.swift
  Projects/Domain/StudentDomain/Testing/Testing.swift
  Projects/Domain/StudentDomain/Testing/UseCase/FetchStudentUseCaseSpy.swift
  Projects/Domain/UserDomain/Sources/UseCase/SaveUserRoleUseCaseImpl.swift
  Projects/Domain/UserDomain/Testing/Testing.swift
  Projects/Domain/UserDomain/Testing/UseCase/LoadUserRoleUseCaseSpy.swift
  Projects/Feature/BaseFeature/Project.swift
  Projects/Feature/InputInformationFeature/Sources/Scene/InputInformationView.swift
  Projects/Feature/StudentDetailFeature/Demo/Resources/LaunchScreen.storyboard
  Projects/Feature/StudentDetailFeature/Demo/Sources/StudentDetailDemoApp.swift
  Projects/Feature/StudentDetailFeature/Interface/DI/StudentDetailBuildable.swift
  Projects/Feature/StudentDetailFeature/Project.swift
  Projects/Feature/StudentDetailFeature/Sources/DI/StudentDetailComponent.swift
  Projects/Feature/StudentDetailFeature/Sources/Intent/StudentDetailIntent.swift
  Projects/Feature/StudentDetailFeature/Sources/Intent/StudentDetailIntentProtocol.swift
  Projects/Feature/StudentDetailFeature/Sources/Model/StudentDetailModel.swift
  Projects/Feature/StudentDetailFeature/Sources/Model/StudentDetailModelProtocol.swift
  Projects/Feature/StudentDetailFeature/Sources/Scene/StudentDetailView.swift
  Projects/Feature/StudentDetailFeature/Tests/StudentDetailFeatureTest.swift
  Projects/Shared/ViewUtil/Sources/Property/ViewNamespaceIDProperty.swift
  Tuist/Dependencies.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#173 🔀 :: 메인 페이지 제작
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/Dependency+Target.swift
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/ModulePaths.swift
  Projects/App/Project.swift
  Projects/App/Sources/Application/DI/AppComponent.swift
  Projects/App/Sources/Application/NeedleGenerated.swift
  Projects/Core/DesignSystem/Resources/Icon/Icons.xcassets/Filter.imageset/Contents.json
  Projects/Core/DesignSystem/Resources/Icon/Icons.xcassets/Filter.imageset/Filter.svg
  Projects/Core/DesignSystem/Resources/Icon/Icons.xcassets/SMSLogo.imageset/Contents.json
  Projects/Core/DesignSystem/Resources/Icon/Icons.xcassets/SMSLogo.imageset/SMSLogo.svg
  Projects/Core/DesignSystem/Resources/Icon/Icons.xcassets/Search.imageset/Contents.json
  Projects/Core/DesignSystem/Resources/Icon/Icons.xcassets/Search.imageset/Search.svg
  Projects/Core/DesignSystem/Resources/Icon/Icons.xcassets/UpArrow.imageset/Contents.json
  Projects/Core/DesignSystem/Resources/Icon/Icons.xcassets/UpArrow.imageset/UpArrow.svg
  Projects/Core/DesignSystem/Sources/Icon/SMSIcon.swift
  Projects/Domain/BaseDomain/Sources/Interceptors/Jwt/JwtInterceptor.swift
  Projects/Domain/FileDomain/Sources/Endpoint/FileEndpoint.swift
  Projects/Domain/StudentDomain/Interface/Entity/SingleStudentEntity.swift
  Projects/Domain/StudentDomain/Sources/DTO/Response/FetchStudentListResponseDTO.swift
  Projects/Feature/InputInformationFeature/Sources/Intent/InputInformationIntent.swift
  Projects/Feature/InputInformationFeature/Sources/Model/InputInformationModel.swift
  Projects/Feature/InputProfileInfoFeature/Sources/Scene/InputProfileInfoView.swift
  Projects/Feature/MainFeature/Interface/MainBuildable.swift
  Projects/Feature/MainFeature/Interface/MainDelegate.swift
  Projects/Feature/MainFeature/Project.swift
  Projects/Feature/MainFeature/Sources/DI/MainComponent.swift
  Projects/Feature/MainFeature/Sources/Intent/MainIntent.swift
  Projects/Feature/MainFeature/Sources/Intent/MainIntentProtocol.swift
  Projects/Feature/MainFeature/Sources/Model/MainModel.swift
  Projects/Feature/MainFeature/Sources/Model/MainModelProtocol.swift
  Projects/Feature/MainFeature/Sources/Scene/MainView.swift
  Projects/Feature/MainFeature/Testing/Testing.swift
  Projects/Feature/MainFeature/Tests/MainFeatureTest.swift
  Projects/Feature/RootFeature/Project.swift
  Projects/Feature/RootFeature/Sources/DI/RootComponent.swift
  Projects/Feature/RootFeature/Sources/Enums/RootSceneType.swift
  Projects/Feature/RootFeature/Sources/Intent/RootIntent.swift
  Projects/Feature/RootFeature/Sources/Intent/RootIntentProtocol.swift
  Projects/Feature/RootFeature/Sources/Scene/RootView.swift
  Tuist/Dependencies.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#181 🔀 :: 정보 기입 완료 후 메인으로 보내기
  Projects/Feature/InputInformationFeature/Sources/Intent/InputInformationIntent.swift
  Projects/Feature/RootFeature/Sources/Model/RootModel.swift
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#185 🔀 :: 로그아웃, 회원탈퇴 제작
  Projects/App/Sources/Application/NeedleGenerated.swift
  Projects/Core/DesignSystem/Resources/Icon/Icons.xcassets/RedLogout.imageset/Contents.json
  Projects/Core/DesignSystem/Resources/Icon/Icons.xcassets/RedLogout.imageset/RedLogout.svg
  Projects/Core/DesignSystem/Resources/Icon/Icons.xcassets/RedPerson.imageset/Contents.json
  Projects/Core/DesignSystem/Resources/Icon/Icons.xcassets/RedPerson.imageset/RedPerson.svg
  Projects/Core/DesignSystem/Sources/Icon/SMSIcon.swift
  Projects/Domain/AuthDomain/Interface/DI/AuthDomainBuildable.swift
  Projects/Domain/AuthDomain/Interface/DataSource/LocalAuthDataSource.swift
  Projects/Domain/AuthDomain/Interface/DataSource/RemoteAuthDataSource.swift
  Projects/Domain/AuthDomain/Interface/Repository/AuthRepository.swift
  Projects/Domain/AuthDomain/Interface/UseCase/LogoutUseCase.swift
  Projects/Domain/AuthDomain/Interface/UseCase/WithdrawalUseCase.swift
  Projects/Domain/AuthDomain/Sources/DI/AuthDomainComponent.swift
  Projects/Domain/AuthDomain/Sources/DataSource/LocalAuthDataSourceImpl.swift
  Projects/Domain/AuthDomain/Sources/DataSource/RemoteAuthDataSourceImpl.swift
  Projects/Domain/AuthDomain/Sources/Endpoint/AuthEndpoint.swift
  Projects/Domain/AuthDomain/Sources/Repository/AuthRepositoryImpl.swift
  Projects/Domain/AuthDomain/Sources/UseCase/LogoutUseCaseImpl.swift
  Projects/Domain/AuthDomain/Sources/UseCase/WithdrawalUseCaseImpl.swift
  Projects/Feature/MainFeature/Interface/MainDelegate.swift
  Projects/Feature/MainFeature/Project.swift
  Projects/Feature/MainFeature/Sources/DI/MainComponent.swift
  Projects/Feature/MainFeature/Sources/Intent/MainIntent.swift
  Projects/Feature/MainFeature/Sources/Intent/MainIntentProtocol.swift
  Projects/Feature/MainFeature/Sources/Model/MainModel.swift
  Projects/Feature/MainFeature/Sources/Model/MainModelProtocol.swift
  Projects/Feature/MainFeature/Sources/Scene/MainView.swift
  Projects/Feature/RootFeature/Sources/Intent/RootIntent.swift
  Projects/Feature/RootFeature/Sources/Scene/RootView.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#184 🔀 :: 메인 - 디테일 연결
  Projects/App/Sources/Application/NeedleGenerated.swift
  Projects/Feature/MainFeature/Project.swift
  Projects/Feature/MainFeature/Sources/DI/MainComponent.swift
  Projects/Feature/MainFeature/Sources/Intent/MainIntent.swift
  Projects/Feature/MainFeature/Sources/Intent/MainIntentProtocol.swift
  Projects/Feature/MainFeature/Sources/Model/MainModel.swift
  Projects/Feature/MainFeature/Sources/Model/MainModelProtocol.swift
  Projects/Feature/MainFeature/Sources/Scene/MainView.swift
  Projects/Feature/StudentDetailFeature/Demo/Sources/StudentDetailDemoApp.swift
  Projects/Feature/StudentDetailFeature/Interface/DI/StudentDetailBuildable.swift
  Projects/Feature/StudentDetailFeature/Sources/DI/StudentDetailComponent.swift
  Projects/Feature/StudentDetailFeature/Sources/Scene/StudentDetailView.swift
  Projects/Shared/ViewUtil/Sources/Property/ViewNamespaceIDProperty.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#188 🔀 :: 학생 리스트 API 필터 적용
  Projects/Domain/StudentDomain/Interface/DTO/Request/FetchStudentListRequestDTO.swift
  Projects/Domain/StudentDomain/Interface/Enums/SortType.swift
  Projects/Domain/StudentDomain/Sources/Endpoint/StudentEndpoint.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#191 🔀 :: 프로필 정보입력 페이지 techStack 삭제 가능하게 변경
  Projects/Feature/InputProfileInfoFeature/Sources/Intent/InputProfileInfoIntent.swift
  Projects/Feature/InputProfileInfoFeature/Sources/Intent/InputProfileInfoIntentProtocol.swift
  Projects/Feature/InputProfileInfoFeature/Sources/Model/InputProfileInfoModel.swift
  Projects/Feature/InputProfileInfoFeature/Sources/Model/InputProfileInfoModelProtocol.swift
  Projects/Feature/InputProfileInfoFeature/Sources/Scene/InputProfileInfoView.swift
  Projects/Feature/TechStackAppendFeature/Demo/Sources/DemoView.swift
  Projects/Feature/TechStackAppendFeature/Interface/TechStackAppendBuildable.swift
  Projects/Feature/TechStackAppendFeature/Sources/DI/TechStackAppendComponent.swift
  Projects/Feature/TechStackAppendFeature/Sources/Model/TechStackAppendModel.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#193 🔀 :: TechStackAppend Feature에 Toast 애니메이션 추가
  Projects/Feature/TechStackAppendFeature/Sources/Intent/TechStackAppendIntent.swift
  Projects/Feature/TechStackAppendFeature/Sources/Intent/TechStackAppendIntentProtocol.swift
  Projects/Feature/TechStackAppendFeature/Sources/Model/TechStackAppendModel.swift
  Projects/Feature/TechStackAppendFeature/Sources/Model/TechStackAppendModelProtocol.swift
  Projects/Feature/TechStackAppendFeature/Sources/Scene/TechStackAppendView.swift
Labels: 0️⃣ Priority: Critical

#189 🔀 :: 자동 로그인 로직 구현
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/Dependency+Target.swift
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/ModulePaths.swift
  Projects/App/Project.swift
  Projects/App/Resources/LaunchScreen.storyboard
  Projects/App/Sources/Application/DI/AppComponent.swift
  Projects/App/Sources/Application/NeedleGenerated.swift
  Projects/Core/DesignSystem/Resources/Icon/Icons.xcassets/SMSSplashLogo.imageset/Contents.json
  Projects/Core/DesignSystem/Resources/Icon/Icons.xcassets/SMSSplashLogo.imageset/SMSSplashLogo.svg
  Projects/Domain/AuthDomain/Interface/DI/AuthDomainBuildable.swift
  Projects/Domain/AuthDomain/Interface/DataSource/RemoteAuthDataSource.swift
  Projects/Domain/AuthDomain/Interface/Repository/AuthRepository.swift
  Projects/Domain/AuthDomain/Interface/UseCase/CheckIsLoggedInUseCase.swift
  Projects/Domain/AuthDomain/Sources/DI/AuthDomainComponent.swift
  Projects/Domain/AuthDomain/Sources/DataSource/RemoteAuthDataSourceImpl.swift
  Projects/Domain/AuthDomain/Sources/Endpoint/AuthEndpoint.swift
  Projects/Domain/AuthDomain/Sources/Repository/AuthRepositoryImpl.swift
  Projects/Domain/AuthDomain/Sources/UseCase/CheckIsLoggedInUseCaseImpl.swift
  Projects/Domain/AuthDomain/Testing/DataSource/RemoteAuthDataSourceSpy.swift
  Projects/Domain/AuthDomain/Testing/Repository/AuthRepositorySpy.swift
  Projects/Domain/BaseDomain/Sources/Interceptors/Jwt/JwtInterceptor.swift
  Projects/Domain/BaseDomain/Sources/RefreshEndpoint/RefreshEndpoint.swift
  Projects/Feature/RootFeature/Project.swift
  Projects/Feature/RootFeature/Sources/DI/RootComponent.swift
  Projects/Feature/RootFeature/Sources/Intent/RootIntent.swift
  Projects/Feature/RootFeature/Sources/Intent/RootIntentProtocol.swift
  Projects/Feature/RootFeature/Sources/Scene/RootView.swift
  Projects/Feature/SplashFeature/Interface/SplashBuildable.swift
  Projects/Feature/SplashFeature/Interface/SplashDelegate.swift
  Projects/Feature/SplashFeature/Project.swift
  Projects/Feature/SplashFeature/Sources/DI/SplashComponent.swift
  Projects/Feature/SplashFeature/Sources/Intent/SplashIntent.swift
  Projects/Feature/SplashFeature/Sources/Intent/SplashIntentProtocol.swift
  Projects/Feature/SplashFeature/Sources/Model/SplashModel.swift
  Projects/Feature/SplashFeature/Sources/Model/SplashModelProtocol.swift
  Projects/Feature/SplashFeature/Sources/Scene/SplashView.swift
  Projects/Feature/SplashFeature/Tests/SplashFeatureTest.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#195 🔀 :: 게스트 기준 학생 이름을 A** 대신 A소금으로 보이도록 변경
  Projects/Feature/MainFeature/Sources/Model/MainModel.swift
Labels: 0️⃣ Priority: Critical

#199 🔀 :: 자동 로그인 로직 변경
  Projects/Domain/AuthDomain/Interface/DataSource/RemoteAuthDataSource.swift
  Projects/Domain/AuthDomain/Interface/Error/AuthDomainError.swift
  Projects/Domain/AuthDomain/Interface/Repository/AuthRepository.swift
  Projects/Domain/AuthDomain/Sources/DTO/Response/VerifyIsInputedUserResponseDTO.swift
  Projects/Domain/AuthDomain/Sources/DataSource/RemoteAuthDataSourceImpl.swift
  Projects/Domain/AuthDomain/Sources/Endpoint/AuthEndpoint.swift
  Projects/Domain/AuthDomain/Sources/Repository/AuthRepositoryImpl.swift
  Projects/Domain/AuthDomain/Sources/UseCase/CheckIsLoggedInUseCaseImpl.swift
  Projects/Domain/AuthDomain/Testing/DataSource/RemoteAuthDataSourceSpy.swift
  Projects/Domain/AuthDomain/Testing/Repository/AuthRepositorySpy.swift
Labels: 0️⃣ Priority: Critical, ⚡️ Simple

#201 🔀 :: 게스트 동작 안되던 현상을,, 해결해봅니다!
  Projects/App/Sources/Application/NeedleGenerated.swift
  Projects/Domain/AuthDomain/Interface/DI/AuthDomainBuildable.swift
  Projects/Domain/AuthDomain/Interface/DataSource/LocalAuthDataSource.swift
  Projects/Domain/AuthDomain/Interface/Repository/AuthRepository.swift
  Projects/Domain/AuthDomain/Interface/UseCase/ClearTokenUseCase.swift
  Projects/Domain/AuthDomain/Sources/DI/AuthDomainComponent.swift
  Projects/Domain/AuthDomain/Sources/DataSource/LocalAuthDataSourceImpl.swift
  Projects/Domain/AuthDomain/Sources/Repository/AuthRepositoryImpl.swift
  Projects/Domain/AuthDomain/Sources/UseCase/ClearTokenUseCaseImpl.swift
  Projects/Domain/AuthDomain/Testing/DataSource/LocalAuthDataSourceSpy.swift
  Projects/Domain/AuthDomain/Testing/Repository/AuthRepositorySpy.swift
  Projects/Feature/MainFeature/Project.swift
  Projects/Feature/MainFeature/Sources/DI/MainComponent.swift
  Projects/Feature/MainFeature/Sources/Intent/MainIntent.swift
  Projects/Feature/MainFeature/Sources/Model/MainModel.swift
  Projects/Feature/MainFeature/Sources/Model/MainModelProtocol.swift
  Projects/Feature/MainFeature/Sources/Scene/MainView.swift
  Projects/Feature/SigninFeature/Sources/DI/SigninComponent.swift
  Projects/Feature/SigninFeature/Sources/Intent/SigninIntent.swift
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#204 🔀 :: 게스트 상태일때 유저의 이름이 **로 뜨는 현상
  Projects/Feature/StudentDetailFeature/Sources/Model/StudentDetailModel.swift
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#210 🔀 :: 드림북 파일 다운로드 시 \(학번이름)-드림북.hwp 으로 변경
  Projects/Feature/StudentDetailFeature/Project.swift
  Projects/Feature/StudentDetailFeature/Sources/Intent/StudentDetailIntent.swift
  Projects/Feature/StudentDetailFeature/Sources/Intent/StudentDetailIntentProtocol.swift
  Projects/Feature/StudentDetailFeature/Sources/Model/HWPDocument.swift
  Projects/Feature/StudentDetailFeature/Sources/Model/StudentDetailModel.swift
  Projects/Feature/StudentDetailFeature/Sources/Model/StudentDetailModelProtocol.swift
  Projects/Feature/StudentDetailFeature/Sources/Scene/StudentDetailView.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#212 🔀 :: 정보 입력 페이지에서 입력들에 Validation 설정
  Projects/Feature/InputCertificateInfoFeature/Sources/Intent/InputCertificateInfoIntent.swift
  Projects/Feature/InputLanguageInfoFeature/Sources/Intent/InputLanguageInfoIntent.swift
  Projects/Feature/InputWorkInfoFeature/Sources/Intent/InputWorkInfoIntent.swift
  Projects/Shared/FoundationUtil/Sources/Array/Array+safe.swift
  Projects/Shared/FoundationUtil/Sources/String/String+isNotEmpty.swift
Labels: 0️⃣ Priority: Critical, ♻️ Refactor

#214 🔀 :: 메인 페이지 refresh 기능 추가
  Projects/App/Sources/Application/NeedleGenerated.swift
  Projects/Feature/MainFeature/Sources/Intent/MainIntent.swift
  Projects/Feature/MainFeature/Sources/Intent/MainIntentProtocol.swift
  Projects/Feature/MainFeature/Sources/Model/MainModel.swift
  Projects/Feature/MainFeature/Sources/Model/MainModelProtocol.swift
  Projects/Feature/MainFeature/Sources/Scene/MainView.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#217 🔀 :: 카메라에서 Video 누를 시 앱 꺼짐 현상
  Projects/App/Sources/Application/NeedleGenerated.swift
  Projects/Core/DesignSystem/Sources/CameraPicker/CameraPicker.swift
Labels: 0️⃣ Priority: Critical, 🐞 Bug
