Repository GSM-MSG/SMS-iOS, pull requests merged in 2023-08, with the labels that each got.

#240 🔀 :: [#239] DreamBook 관련된 코드 지우기
  Projects/Domain/FileDomain/Interface/DI/FileDomainBuildable.swift
  Projects/Domain/FileDomain/Interface/DataSource/RemoteFileDataSource.swift
  Projects/Domain/FileDomain/Interface/Repository/FileRepository.swift
  Projects/Domain/FileDomain/Interface/UseCase/DreamBookUploadUseCase.swift
  Projects/Domain/FileDomain/Sources/DI/FileDomainComponent.swift
  Projects/Domain/FileDomain/Sources/DTO/Response/DreamBookUploadResponseDTO.swift
  Projects/Domain/FileDomain/Sources/DataSource/RemoteFileDataSourceImpl.swift
  Projects/Domain/FileDomain/Sources/Endpoint/FileEndpoint.swift
  Projects/Domain/FileDomain/Sources/Repository/FileRepositoryImpl.swift
  Projects/Domain/FileDomain/Sources/UseCase/DreamBookUploadUseCaseImpl.swift
  Projects/Domain/StudentDomain/Interface/DTO/Request/StudentRequestDTO.swift
  Projects/Domain/StudentDomain/Interface/Entity/StudentDetailEntity.swift
  Projects/Domain/StudentDomain/Sources/DTO/Response/FetchStudentDetailByTeacherResponseDTO.swift
  Projects/Feature/InputInformationFeature/Sources/DI/InputInformationComponent.swift
  Projects/Feature/InputInformationFeature/Sources/Intent/InputInformationIntent.swift
  Projects/Feature/StudentDetailFeature/Sources/Intent/StudentDetailIntent.swift
  Projects/Feature/StudentDetailFeature/Sources/Intent/StudentDetailIntentProtocol.swift
  Projects/Feature/StudentDetailFeature/Sources/Model/HWPDocument.swift
  Projects/Feature/StudentDetailFeature/Sources/Model/StudentDetailModel.swift
  Projects/Feature/StudentDetailFeature/Sources/Model/StudentDetailModelProtocol.swift
  Projects/Feature/StudentDetailFeature/Sources/Scene/StudentDetailView.swift
Labels: 2️⃣ Priority: Medium, ♻️ Refactor, 🪡 Want

#246 🔀 :: [#244] Error Color 추가 및 ErrorCTAButton 추가
  Projects/Core/DesignSystem/Demo/Sources/DemoView.swift
  Projects/Core/DesignSystem/Resources/Color/Error.xcassets/Contents.json
  Projects/Core/DesignSystem/Resources/Color/Error.xcassets/E1.colorset/Contents.json
  Projects/Core/DesignSystem/Resources/Color/Error.xcassets/E2.colorset/Contents.json
  Projects/Core/DesignSystem/Resources/Color/Error.xcassets/E3.colorset/Contents.json
  Projects/Core/DesignSystem/Sources/Button/CTA/CTAButtonStyle.swift
  Projects/Core/DesignSystem/Sources/Color/Color+sms.swift
  Projects/Core/DesignSystem/Sources/Color/SMSColorSystem+Error.swift
  Projects/Core/DesignSystem/Sources/Color/SMSColorSystem+System.swift
  Projects/Core/DesignSystem/Sources/TextField/SMSIconTextField.swift
  Projects/Core/DesignSystem/Sources/TextField/SMSTextField.swift
  Projects/Feature/InputProfileInfoFeature/Sources/Scene/InputProfileInfoView.swift
  Projects/Feature/MainFeature/Sources/Scene/MainView.swift
Labels: 1️⃣ Priority: High, ⚡️ Simple

#247 🔀 :: [#225] 정보 입력 ... View를 ProgressBar로 수정
  Projects/Core/DesignSystem/Demo/Sources/DemoView.swift
  Projects/Core/DesignSystem/Sources/PageControl/SMSPageControl.swift
  Projects/Feature/InputCertificateInfoFeature/Sources/Scene/InputCertificateInfoView.swift
  Projects/Feature/InputInformationBaseFeature/Sources/InputInformationPageTitleView.swift
  Projects/Feature/InputLanguageInfoFeature/Sources/Scene/InputLanguageInfoView.swift
  Projects/Feature/InputMilitaryInfoFeature/Sources/Scene/InputMilitaryInfoView.swift
  Projects/Feature/InputPrizeInfoFeature/Sources/Scene/InputPrizeInfoView.swift
  Projects/Feature/InputProfileInfoFeature/Sources/Scene/InputProfileInfoView.swift
  Projects/Feature/InputProjectInfoFeature/Sources/Scene/InputProjectInfoView.swift
  Projects/Feature/InputSchoolLifeInfoFeature/Sources/Scene/InputSchoolLifeInfoView.swift
  Projects/Feature/InputWorkInfoFeature/Sources/Scene/InputWorkInfoView.swift
Labels: 2️⃣ Priority: Medium, ♻️ Refactor

#250 🔀 :: 디테일 페이지 수정
  Projects/Core/DesignSystem/Sources/TextField/SMSIconTextField.swift
  Projects/Core/DesignSystem/Sources/TextField/SMSTextField.swift
  Projects/Domain/AuthDomain/Sources/Endpoint/AuthEndpoint.swift
  Projects/Feature/InputProjectInfoFeature/Sources/Scene/InputProjectInfoView.swift
  Projects/Feature/InputWorkInfoFeature/Sources/Model/InputWorkInfoModel.swift
  Projects/Feature/MainFeature/Sources/Scene/MainView.swift
  Projects/Feature/MyPageFeature/Sources/Scene/MyPageProjectView.swift
  Projects/Feature/StudentDetailFeature/Sources/Scene/StudentDetailView.swift
  Projects/Feature/StudentDetailFeature/Sources/Scene/View/PrizeRowView.swift
  Projects/Feature/StudentDetailFeature/Sources/Scene/View/ProjectRowView.swift
  Projects/Feature/StudentDetailFeature/Sources/Scene/View/StudentDetailSubTitleWrapper.swift
  Projects/Feature/StudentDetailFeature/Sources/Scene/View/StudentDetailTitleWrapper.swift
  Projects/Feature/TechStackAppendFeature/Sources/Scene/TechStackAppendView.swift
  Projects/Shared/FoundationUtil/Sources/Collection/Collection+isNotEmpty.swift
  Projects/Shared/Validator/Project.swift
  Projects/Shared/Validator/Sources/RegexValidator.swift
  Projects/Shared/ViewUtil/Project.swift
  Projects/Shared/ViewUtil/Sources/Extensions/Environment+UIScreenSize.swift
  Projects/Shared/ViewUtil/Sources/UtilView/HighlightedText.swift
Labels: 1️⃣ Priority: High, ♻️ Refactor, ✨ Feature

#253 🔀 :: 245 ios cd
  .github/workflows/CD/Decrypt.sh
  .github/workflows/CD/Keychain.sh
  .github/workflows/sms-ios-cd.yml
  .github/workflows/sms-ios-ci.yml
  .gitignore
  Gemfile
  Gemfile.lock
  Makefile
  Plugin/ConfigurationPlugin/ProjectDescriptionHelpers/Configuration+Ext.swift
  Plugin/ConfigurationPlugin/ProjectDescriptionHelpers/Path+XCConfig.swift
  Projects/App/Project.swift
  Tuist/ProjectDescriptionHelpers/GenerateEnvironment.swift
  Tuist/ProjectDescriptionHelpers/Project+Template.swift
  Tuist/Signing/SMS.PROD.mobileprovision.gpg
  Tuist/Signing/SMS.cer.encrypted
  Tuist/Signing/SMS.p12.encrypted
  Tuist/master.key.gpg
  XCConfig.zip.gpg
  XCConfig/Shared.xcconfig
  fastlane/.env.default.gpg
  fastlane/Appfile
  fastlane/Fastfile
  fastlane/Pluginfile
  fastlane/SMS-AppStoreKey.json.gpg
  fastlane/metadata/copyright.txt
  fastlane/metadata/ko/.gitkeep
  fastlane/metadata/ko/apple_tv_privacy_policy.txt
  fastlane/metadata/ko/description.txt
  fastlane/metadata/ko/keywords.txt
  fastlane/metadata/ko/marketing_url.txt
  fastlane/metadata/ko/name.txt
  fastlane/metadata/ko/privacy_url.txt
  fastlane/metadata/ko/promotional_text.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/ko/subtitle.txt
  fastlane/metadata/ko/support_url.txt
  fastlane/metadata/primary_category.txt
  fastlane/metadata/primary_first_sub_category.txt
  fastlane/metadata/primary_second_sub_category.txt
  fastlane/metadata/secondary_category.txt
  fastlane/metadata/secondary_first_sub_category.txt
  fastlane/metadata/secondary_second_sub_category.txt
  fastlane/screenshots/README.txt
Labels: 1️⃣ Priority: High, 🌏 Deploy, 📝 Docs, 🪡 Want

#256 🔀 :: [#255] BaseDomain XCConfig 연결
  Projects/Domain/BaseDomain/Project.swift
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#257 🔀 :: 1.1.0 release
  Projects/App/Sources/Application/NeedleGenerated.swift
  Projects/App/Support/Info.plist
  Projects/Feature/MyPageFeature/Sources/Scene/MyPageView.swift
Labels: 🌏 Deploy

#260 🔀 :: [#259] MyPage API 수정사항 반영
  Projects/Domain/UserDomain/Sources/DTO/Response/FetchMyProfileResponseDTO.swift
Labels: 0️⃣ Priority: Critical, 📝 Docs

#262 🔀 :: [#261] 학생 상세 정보 API 수정사항 반영
  Projects/Domain/StudentDomain/Sources/DTO/Response/FetchStudentDetailByGuestResponseDTO.swift
  Projects/Domain/StudentDomain/Sources/DTO/Response/FetchStudentDetailByStudentResponseDTO.swift
  Projects/Domain/StudentDomain/Sources/DTO/Response/FetchStudentDetailByTeacherResponseDTO.swift
Labels: 0️⃣ Priority: Critical, 📝 Docs

#265 🔀 :: [#264] App모듈 xcconfig 설정
  Projects/App/Project.swift
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#266 🔀 :: 1.1.1 release
  Projects/App/Support/Info.plist
Labels: 🌏 Deploy

#263 🔀 :: [#252] 필수요소 검사해서 에러 띄우기
  Projects/Feature/FilterFeature/Sources/Scene/FilterView.swift
  Projects/Feature/InputPrizeInfoFeature/Sources/Intent/InputPrizeInfoIntent.swift
  Projects/Feature/InputPrizeInfoFeature/Sources/Model/InputPrizeInfoModel.swift
  Projects/Feature/InputPrizeInfoFeature/Sources/Model/InputPrizeInfoModelProtocol.swift
  Projects/Feature/InputPrizeInfoFeature/Sources/Scene/InputPrizeInfoView.swift
  Projects/Feature/InputProfileInfoFeature/Sources/Scene/InputProfileInfoView.swift
  Projects/Feature/InputProjectInfoFeature/Sources/Intent/InputProjectInfoIntent.swift
  Projects/Feature/InputProjectInfoFeature/Sources/Model/InputProjectInfoModel.swift
  Projects/Feature/InputProjectInfoFeature/Sources/Model/InputProjectInfoModelProtocol.swift
  Projects/Feature/InputProjectInfoFeature/Sources/Scene/InputProjectInfoView.swift
  Projects/Feature/MyPageFeature/Project.swift
  Projects/Feature/MyPageFeature/Sources/Intent/MyPageIntent.swift
  Projects/Feature/MyPageFeature/Sources/Intent/MyPagePrizeIntentProtocol.swift
  Projects/Feature/MyPageFeature/Sources/Intent/MyPageProfileIntent.swift
  Projects/Feature/MyPageFeature/Sources/Intent/MyPageProjectIntent.swift
  Projects/Feature/MyPageFeature/Sources/Model/MyPageModel.swift
  Projects/Feature/MyPageFeature/Sources/Model/MyPageModelProtocol.swift
  Projects/Feature/MyPageFeature/Sources/Model/MyPagePrizeModel.swift
  Projects/Feature/MyPageFeature/Sources/Model/MyPageProfileModel.swift
  Projects/Feature/MyPageFeature/Sources/Model/MyPageProjectModel.swift
  Projects/Feature/MyPageFeature/Sources/Scene/MyPagePrizeView.swift
  Projects/Feature/MyPageFeature/Sources/Scene/MyPageProfileView.swift
  Projects/Feature/MyPageFeature/Sources/Scene/MyPageProjectView.swift
  Projects/Feature/MyPageFeature/Sources/Scene/MyPageView.swift
Labels: 1️⃣ Priority: High, ✨ Feature
