Repository GSM-MSG/SMS-iOS, pull requests merged in 2023-04, with the labels that each got.

#5 🔀 :: MVI 세팅
  Projects/App/Project.swift
  Projects/App/Sources/Application/AppDelegate.swift
  Projects/App/Sources/Application/SceneDelegate.swift
  Projects/Feature/BaseFeature/Sources/Feature.swift
  Projects/Feature/BaseFeature/Sources/MVIContainer.swift
Labels: 1️⃣ Priority: High, ⚙ Setting

#11 🔀 :: ColorDesignSystem 제작
  Projects/Core/DesignSystem/Project.swift
  Projects/Core/DesignSystem/Resources/Neutral.xcassets/Contents.json
  Projects/Core/DesignSystem/Resources/Neutral.xcassets/N10.colorset/Contents.json
  Projects/Core/DesignSystem/Resources/Neutral.xcassets/N20.colorset/Contents.json
  Projects/Core/DesignSystem/Resources/Neutral.xcassets/N30.colorset/Contents.json
  Projects/Core/DesignSystem/Resources/Neutral.xcassets/N40.colorset/Contents.json
  Projects/Core/DesignSystem/Resources/Neutral.xcassets/N50.colorset/Contents.json
  Projects/Core/DesignSystem/Resources/Primary.xcassets/Contents.json
  Projects/Core/DesignSystem/Resources/Primary.xcassets/P1.colorset/Contents.json
  Projects/Core/DesignSystem/Resources/Primary.xcassets/P2.colorset/Contents.json
  Projects/Core/DesignSystem/Resources/Primary.xcassets/P3.colorset/Contents.json
  Projects/Core/DesignSystem/Resources/Sub.xcassets/Contents.json
  Projects/Core/DesignSystem/Resources/Sub.xcassets/S1.colorset/Contents.json
  Projects/Core/DesignSystem/Resources/Sub.xcassets/S2.colorset/Contents.json
  Projects/Core/DesignSystem/Resources/Sub.xcassets/S3.colorset/Contents.json
  Projects/Core/DesignSystem/Resources/System.xcassets/Black.colorset/Contents.json
  Projects/Core/DesignSystem/Resources/System.xcassets/Contents.json
  Projects/Core/DesignSystem/Resources/System.xcassets/Error.colorset/Contents.json
  Projects/Core/DesignSystem/Resources/System.xcassets/Positive.colorset/Contents.json
  Projects/Core/DesignSystem/Resources/System.xcassets/White.colorset/Contents.json
  Projects/Core/DesignSystem/Sources/Color/Color+sms.swift
  Projects/Core/DesignSystem/Sources/Color/SMSColorSystem+Neutral.swift
  Projects/Core/DesignSystem/Sources/Color/SMSColorSystem+Primary.swift
  Projects/Core/DesignSystem/Sources/Color/SMSColorSystem+Sub.swift
  Projects/Core/DesignSystem/Sources/Color/SMSColorSystem+System.swift
  Projects/Core/DesignSystem/Sources/Color/SMSColorable.swift
  Projects/Core/DesignSystem/Sources/Feature.swift
  Projects/Shared/DateUtil/Tests/DateFormatUtilSpec.swift
Labels: 1️⃣ Priority: High, ⚙ Setting

#16 🔀 :: 로그인 UseCase Interface
  .tuist-version
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/Dependency+Target.swift
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/ModulePaths.swift
  Projects/Domain/AuthDomain/Interface/LoginUseCase.swift
  Projects/Domain/AuthDomain/Project.swift
  Projects/Domain/AuthDomain/Sources/Source.swift
  Projects/Domain/AuthDomain/Testing/Testing.swift
  Projects/Domain/AuthDomain/Tests/AuthDomainTest.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#14 🔀 :: SwiftUI에서 사용하게 변경
  Projects/Core/DesignSystem/Sources/Color/Color+sms.swift
  Projects/Core/DesignSystem/Sources/Color/SMSColorSystem+Neutral.swift
  Projects/Core/DesignSystem/Sources/Color/SMSColorSystem+Primary.swift
  Projects/Core/DesignSystem/Sources/Color/SMSColorSystem+Sub.swift
  Projects/Core/DesignSystem/Sources/Color/SMSColorSystem+System.swift
  Projects/Core/DesignSystem/Sources/Color/SMSColorable.swift
Labels: 0️⃣ Priority: Critical, ⚙ Setting

#18 🔀 :: 로그인 기능 추가
  Projects/Domain/AuthDomain/Interface/Error/AuthDomainError.swift
  Projects/Domain/AuthDomain/Interface/Repository/AuthRepository.swift
  Projects/Domain/AuthDomain/Interface/UseCase/LoginUseCase.swift
  Projects/Domain/AuthDomain/Project.swift
  Projects/Domain/AuthDomain/Sources/DataSource/Impl/RemoteAuthDataSourceImpl.swift
  Projects/Domain/AuthDomain/Sources/DataSource/RemoteAuthDataSource.swift
  Projects/Domain/AuthDomain/Sources/Endpoint/AuthEndpoint.swift
  Projects/Domain/AuthDomain/Sources/Repository/AuthRepositoryImpl.swift
  Projects/Domain/AuthDomain/Sources/Source.swift
  Projects/Domain/AuthDomain/Sources/UseCase/LoginUseCaseImpl.swift
  Projects/Domain/BaseDomain/Sources/Base/BaseRetemoteDataSource.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#22 🔀 :: JwtTokenDTO API 명세서와 일치화
  Projects/Domain/BaseDomain/Sources/Interceptors/Jwt/JwtTokenDTO.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#26 🔀 :: 로그인 로직 Unit Test
  Projects/Domain/AuthDomain/Interface/DataSource/RemoteAuthDataSource.swift
  Projects/Domain/AuthDomain/Interface/Error/AuthDomainError.swift
  Projects/Domain/AuthDomain/Sources/DataSource/RemoteAuthDataSourceImpl.swift
  Projects/Domain/AuthDomain/Testing/DataSource/RemoteAuthDataSourceSpy.swift
  Projects/Domain/AuthDomain/Testing/Repository/AuthRepositorySpy.swift
  Projects/Domain/AuthDomain/Testing/Testing.swift
  Projects/Domain/AuthDomain/Testing/UseCase/LoginUseCaseSpy.swift
  Projects/Domain/AuthDomain/Tests/AuthDomainTest.swift
  Projects/Domain/AuthDomain/Tests/Repository/AuthRepositorySpec.swift
  Projects/Domain/AuthDomain/Tests/UseCase/LoginUseCaseSpec.swift
  Projects/Domain/BaseDomain/Sources/Interceptors/Jwt/JwtAuthorizable.swift
  Projects/Domain/BaseDomain/Sources/Interceptors/Jwt/JwtInterceptor.swift
Labels: 2️⃣ Priority: Medium, ✅ Test
