Repository GSM-MSG/SMS-iOS, pull requests merged in 2023-11, with the labels that each got.

#254 🔀 ::[#251]FoundationUtil / notContains 제작
  Projects/Feature/InputPrizeInfoFeature/Sources/Intent/InputPrizeInfoIntent.swift
  Projects/Feature/InputProjectInfoFeature/Sources/Intent/InputProjectInfoIntent.swift
  Projects/Feature/MyPageFeature/Sources/Intent/MyPagePrizeIntentProtocol.swift
  Projects/Feature/MyPageFeature/Sources/Intent/MyPageProjectIntent.swift
  Projects/Shared/FoundationUtil/Sources/Collection/Collection+notContains.swift
Labels: ♻️ Refactor

#312 🔀 :: [#311] 정보입력 UI 간소화
  Projects/Domain/StudentDomain/Interface/DTO/Request/InputStudentInformationRequestDTO.swift
  Projects/Feature/InputInformationBaseFeature/Sources/InputInformationPageTitleView.swift
  Projects/Feature/InputInformationFeature/Sources/Intent/InputInformationIntent.swift
  Projects/Feature/InputProfileInfoFeature/Interface/InputProfileDelegate.swift
  Projects/Feature/InputProfileInfoFeature/Sources/Intent/InputProfileInfoIntent.swift
  Projects/Feature/InputProfileInfoFeature/Sources/Intent/InputProfileInfoIntentProtocol.swift
  Projects/Feature/InputProfileInfoFeature/Sources/Model/InputProfileInfoModel.swift
  Projects/Feature/InputProfileInfoFeature/Sources/Model/InputProfileInfoModelProtocol.swift
  Projects/Feature/InputProfileInfoFeature/Sources/Scene/InputProfileInfoView.swift
  Projects/Feature/InputProfileInfoFeature/Tests/InputProfileInfoFeatureTest.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#310 🔀 :: [#309] 학생정보기입 API 리펙토링
  Projects/Domain/StudentDomain/Interface/DTO/Request/InputStudentInformationRequestDTO.swift
  Projects/Feature/InputInformationFeature/Sources/DI/InputInformationComponent.swift
  Projects/Feature/InputInformationFeature/Sources/Intent/InputInformationIntent.swift
  Projects/Feature/InputInformationFeature/Sources/Intent/InputInformationIntentProtocol.swift
  Projects/Feature/InputInformationFeature/Sources/Model/InputInformationModel.swift
  Projects/Feature/InputInformationFeature/Sources/Model/InputInformationModelProtocol.swift
  Projects/Feature/InputInformationFeature/Sources/Scene/InputInformationView.swift
Labels: 1️⃣ Priority: High, ♻️ Refactor
