Repository GSM-MSG/SMS-iOS, pull requests merged in 2023-05, with the labels that each got.

#27 🔀 :: Signin 페이지 제작
  .tuist-version
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/Dependency+SPM.swift
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/Dependency+Target.swift
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/ModulePaths.swift
  Projects/App/.swiftlint.yml
  Projects/App/Project.swift
  Projects/App/Sources/Application/AppDelegate.swift
  Projects/App/Sources/Application/DI/AppComponent.swift
  Projects/App/Sources/Application/NeedleGenerated.swift
  Projects/App/Sources/Application/SMSApp.swift
  Projects/App/Sources/Application/SceneDelegate.swift
  Projects/App/Support/Info.plist
  Projects/Core/DesignSystem/Resources/Image/Images.xcassets/Background.imageset/Background 1.png
  Projects/Core/DesignSystem/Resources/Image/Images.xcassets/Background.imageset/Background 2.png
  Projects/Core/DesignSystem/Resources/Image/Images.xcassets/Background.imageset/Background.png
  Projects/Core/DesignSystem/Resources/Image/Images.xcassets/Background.imageset/Contents.json
  Projects/Core/DesignSystem/Resources/Image/Images.xcassets/Contents.json
  Projects/Core/DesignSystem/Sources/Image/SMSImage.swift
  Projects/Core/JwtStore/Interface/DI/JwtStoreBuildable.swift
  Projects/Core/JwtStore/Sources/DI/JwtStoreComponent.swift
  Projects/Domain/AuthDomain/Interface/DI/AuthDomainBuildable.swift
  Projects/Domain/AuthDomain/Sources/DI/AuthDomainComponent.swift
  Projects/Feature/BaseFeature/Project.swift
  Projects/Feature/BaseFeature/Sources/MVIContainer.swift
  Projects/Feature/SigninFeature/Interface/SigninBuildable.swift
  Projects/Feature/SigninFeature/Project.swift
  Projects/Feature/SigninFeature/Sources/DI/SigninComponent.swift
  Projects/Feature/SigninFeature/Sources/Intent/SigninIntent.swift
  Projects/Feature/SigninFeature/Sources/Intent/SigninIntentProtocol.swift
  Projects/Feature/SigninFeature/Sources/Model/SigninModel.swift
  Projects/Feature/SigninFeature/Sources/Model/SigninModelProtocol.swift
  Projects/Feature/SigninFeature/Sources/Scene/GAuthButtonView.swift
  Projects/Feature/SigninFeature/Sources/Scene/SigninView.swift
  Projects/Feature/SigninFeature/Support/Info.plist
  Projects/Feature/SigninFeature/Tests/SigninFeatureTest.swift
  Projects/Shared/KeychainModule/Interface/DI/KeychainBuildable.swift
  Projects/Shared/KeychainModule/Sources/DI/KeychainComponent.swift
  Scripts/NeedleRunScript.sh
  Tuist/Dependencies.swift
  Tuist/ProjectDescriptionHelpers/Action+Template.swift
Labels: 0️⃣ Priority: Critical, ⚙ Setting, ✨ Feature

#32 🔀 :: SMSIcon 디자인 시스템
  .gitignore
  Projects/Core/DesignSystem/Resources/Icon/Icons.xcassets/Camera.imageset/Camera 1.svg
  Projects/Core/DesignSystem/Resources/Icon/Icons.xcassets/Camera.imageset/Camera 2.svg
  Projects/Core/DesignSystem/Resources/Icon/Icons.xcassets/Camera.imageset/Camera.svg
  Projects/Core/DesignSystem/Resources/Icon/Icons.xcassets/Camera.imageset/Contents.json
  Projects/Core/DesignSystem/Resources/Icon/Icons.xcassets/Check.imageset/Check 1.svg
  Projects/Core/DesignSystem/Resources/Icon/Icons.xcassets/Check.imageset/Check 2.svg
  Projects/Core/DesignSystem/Resources/Icon/Icons.xcassets/Check.imageset/Check.svg
  Projects/Core/DesignSystem/Resources/Icon/Icons.xcassets/Check.imageset/Contents.json
  Projects/Core/DesignSystem/Resources/Icon/Icons.xcassets/Contents.json
  Projects/Core/DesignSystem/Resources/Icon/Icons.xcassets/DownChevron.imageset/ArrowDown 1.svg
  Projects/Core/DesignSystem/Resources/Icon/Icons.xcassets/DownChevron.imageset/ArrowDown 2.svg
  Projects/Core/DesignSystem/Resources/Icon/Icons.xcassets/DownChevron.imageset/ArrowDown.svg
  Projects/Core/DesignSystem/Resources/Icon/Icons.xcassets/DownChevron.imageset/Contents.json
  Projects/Core/DesignSystem/Resources/Icon/Icons.xcassets/LeftArrow.imageset/Contents.json
  Projects/Core/DesignSystem/Resources/Icon/Icons.xcassets/LeftArrow.imageset/RightArrow 1.svg
  Projects/Core/DesignSystem/Resources/Icon/Icons.xcassets/LeftArrow.imageset/RightArrow 2.svg
  Projects/Core/DesignSystem/Resources/Icon/Icons.xcassets/LeftArrow.imageset/RightArrow.svg
  Projects/Core/DesignSystem/Resources/Icon/Icons.xcassets/Plus.imageset/Contents.json
  Projects/Core/DesignSystem/Resources/Icon/Icons.xcassets/Plus.imageset/Plus 1.svg
  Projects/Core/DesignSystem/Resources/Icon/Icons.xcassets/Plus.imageset/Plus 2.svg
  Projects/Core/DesignSystem/Resources/Icon/Icons.xcassets/Plus.imageset/Plus.svg
  Projects/Core/DesignSystem/Resources/Icon/Icons.xcassets/SmallPlus.imageset/Contents.json
  Projects/Core/DesignSystem/Resources/Icon/Icons.xcassets/SmallPlus.imageset/SmallPlus 1.png
  Projects/Core/DesignSystem/Resources/Icon/Icons.xcassets/SmallPlus.imageset/SmallPlus 2.png
  Projects/Core/DesignSystem/Resources/Icon/Icons.xcassets/SmallPlus.imageset/SmallPlus.png
  Projects/Core/DesignSystem/Resources/Icon/Icons.xcassets/Xmark.imageset/Contents.json
  Projects/Core/DesignSystem/Resources/Icon/Icons.xcassets/Xmark.imageset/Xmark 1.svg
  Projects/Core/DesignSystem/Resources/Icon/Icons.xcassets/Xmark.imageset/Xmark 2.svg
  Projects/Core/DesignSystem/Resources/Icon/Icons.xcassets/Xmark.imageset/Xmark.svg
  Projects/Core/DesignSystem/Sources/Icon/SMSIcon.swift
Labels: 1️⃣ Priority: High, ⚙ Setting

#39 🔀 :: Appearance Light로 고정
  Projects/App/Support/Info.plist
Labels: 3️⃣ Priority: Low, ⚙ Setting

#42 🔀 :: SMSIcon의 renderingMode를 생성자로 받도록 변경
  Projects/Core/DesignSystem/Sources/Icon/SMSIcon.swift
Labels: 1️⃣ Priority: High, ⚡️ Simple

#43 🔀 :: Design System - Chip 제작
  Projects/Core/DesignSystem/Sources/Chip/SMSChip.swift
  Projects/Core/DesignSystem/Sources/Chip/SMSChipButtonStyle.swift
Labels: 2️⃣ Priority: Medium, ✨ Feature

#48 🔀 :: 좌측 상단에 Title을 쉽게 만드는 WrapperView
  Projects/Core/DesignSystem/Demo/Sources/DemoView.swift
  Projects/Core/DesignSystem/Sources/TitleWrapperView/TitleWrapperPosition.swift
  Projects/Core/DesignSystem/Sources/TitleWrapperView/TitleWrapperView.swift
  Projects/Core/DesignSystem/Sources/TitleWrapperView/TitleWrapperViewModifier.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#50 🔀 :: smsBackButton modifier 추가
  Projects/Core/DesignSystem/Demo/Sources/DemoView.swift
  Projects/Core/DesignSystem/Sources/Extension/View+smsBackButton.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#52 🔀 :: Script에 signal 감지로 취소 감지
  Scripts/CodeSigning.swift
  Scripts/GenerateModule.swift
  Scripts/InitEnvironment.swift
  Scripts/NewDependency.swift
Labels: 3️⃣ Priority: Low, ⚡️ Simple

#56 🔀 :: Navigation Delegate 중복 제거
  Projects/Core/DesignSystem/Sources/Extension/View+smsBackButton.swift
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#66 🔀 :: SMSTextField 패딩 변경
  Projects/Core/DesignSystem/Sources/TextField/SMSTextField.swift
Labels: 1️⃣ Priority: High, 🐞 Bug

#69 🔀 :: 이미지 & 카메라 Picker
  Projects/Core/DesignSystem/Sources/CameraPicker/CameraPicker.swift
  Projects/Core/DesignSystem/Sources/ImagePicker/MiltipleImagePicker.swift
  Projects/Core/DesignSystem/Sources/ImagePicker/PickedImage.swift
  Projects/Core/DesignSystem/Sources/ImagePicker/SingleImagePicker.swift
Labels: 1️⃣ Priority: High, ✨ Feature

#71 🔀 :: 정보 입력 - 근무 조건 페이지 UI
  Projects/App/Sources/Application/NeedleGenerated.swift
  Projects/Feature/InputInformationFeature/Sources/DI/InputInformationComponent.swift
  Projects/Feature/InputInformationFeature/Sources/Intent/InputInformationIntent.swift
  Projects/Feature/InputInformationFeature/Sources/Intent/InputInformationIntentProtocol.swift
  Projects/Feature/InputInformationFeature/Sources/Scene/InputInformationView.swift
  Projects/Feature/InputMilitaryInfoFeature/Sources/DI/InputMilitaryInfoComponent.swift
  Projects/Feature/InputMilitaryInfoFeature/Sources/Intent/InputMilitaryInfoIntent.swift
  Projects/Feature/InputWorkInfoFeature/Interface/InputWorkDelegate.swift
  Projects/Feature/InputWorkInfoFeature/Interface/InputWorkInfoBuildable.swift
  Projects/Feature/InputWorkInfoFeature/Sources/DI/InputWorkInfoComponent.swift
  Projects/Feature/InputWorkInfoFeature/Sources/Intent/InputWorkInfoIntent.swift
  Projects/Feature/InputWorkInfoFeature/Sources/Intent/InputWorkInfoIntentProtocol.swift
  Projects/Feature/InputWorkInfoFeature/Sources/Model/InputWorkInfoModel.swift
  Projects/Feature/InputWorkInfoFeature/Sources/Model/InputWorkInfoModelProtocol.swift
  Projects/Feature/InputWorkInfoFeature/Sources/Scene/InputWorkInfoView.swift
Labels: 1️⃣ Priority: High, ✨ Feature

#73 🔀 :: 정보 입력 - 병역 정보 입력 페이지
  Projects/App/Sources/Application/NeedleGenerated.swift
  Projects/Feature/InputInformationFeature/Sources/DI/InputInformationComponent.swift
  Projects/Feature/InputInformationFeature/Sources/Intent/InputInformationIntent.swift
  Projects/Feature/InputInformationFeature/Sources/Intent/InputInformationIntentProtocol.swift
  Projects/Feature/InputInformationFeature/Sources/Scene/InputInformationView.swift
  Projects/Feature/InputMilitaryInfoFeature/Interface/InputMilitaryDelegate.swift
  Projects/Feature/InputMilitaryInfoFeature/Interface/InputMilitaryInfoBuildable.swift
  Projects/Feature/InputMilitaryInfoFeature/Sources/DI/InputMilitaryInfoComponent.swift
  Projects/Feature/InputMilitaryInfoFeature/Sources/Intent/InputMilitaryInfoIntent.swift
  Projects/Feature/InputMilitaryInfoFeature/Sources/Intent/InputMilitaryInfoIntentProtocol.swift
  Projects/Feature/InputMilitaryInfoFeature/Sources/Model/InputMilitaryInfoModel.swift
  Projects/Feature/InputMilitaryInfoFeature/Sources/Model/InputMilitaryInfoModelProtocol.swift
  Projects/Feature/InputMilitaryInfoFeature/Sources/Scene/InputMilitaryInfoView.swift
  Projects/Feature/InputMilitaryInfoFeature/Tests/InputMilitaryInfoFeatureTest.swift
Labels: 1️⃣ Priority: High, ✅ Test, ✨ Feature

#77 🔀 :: 정보 입력 - 자격증 정보 입력 페이지 UI
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/Dependency+Target.swift
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/ModulePaths.swift
  Projects/App/Sources/Application/NeedleGenerated.swift
  Projects/Core/DesignSystem/Resources/Icon/Icons.xcassets/Trash.imageset/Contents.json
  Projects/Core/DesignSystem/Resources/Icon/Icons.xcassets/Trash.imageset/trash 1.svg
  Projects/Core/DesignSystem/Resources/Icon/Icons.xcassets/Trash.imageset/trash 2.svg
  Projects/Core/DesignSystem/Resources/Icon/Icons.xcassets/Trash.imageset/trash.svg
  Projects/Core/DesignSystem/Sources/Icon/SMSIcon.swift
  Projects/Domain/BaseDomain/Project.swift
  Projects/Feature/BaseFeature/Project.swift
  Projects/Feature/InputCertificateInfoFeature/Interface/InputCertificateDelegate.swift
  Projects/Feature/InputCertificateInfoFeature/Interface/InputCertificateInfoBuildable.swift
  Projects/Feature/InputCertificateInfoFeature/Sources/DI/InputCertificateInfoComponent.swift
  Projects/Feature/InputCertificateInfoFeature/Sources/Intent/InputCertificateInfoIntent.swift
  Projects/Feature/InputCertificateInfoFeature/Sources/Intent/InputCertificateInfoIntentProtocol.swift
  Projects/Feature/InputCertificateInfoFeature/Sources/Model/InputCertificateInfoModel.swift
  Projects/Feature/InputCertificateInfoFeature/Sources/Model/InputCertificateInfoModelProtocol.swift
  Projects/Feature/InputCertificateInfoFeature/Sources/Scene/InputCertificateInfoView.swift
  Projects/Feature/InputInformationFeature/Sources/DI/InputInformationComponent.swift
  Projects/Feature/InputInformationFeature/Sources/Intent/InputInformationIntent.swift
  Projects/Feature/InputInformationFeature/Sources/Intent/InputInformationIntentProtocol.swift
  Projects/Feature/InputInformationFeature/Sources/Model/InputInformationModelProtocol.swift
  Projects/Feature/InputInformationFeature/Sources/Scene/InputInformationView.swift
  Projects/Shared/FoundationUtil/Project.swift
  Projects/Shared/FoundationUtil/Sources/Array+safe.swift
  Projects/Shared/FoundationUtil/Tests/FoundationUtilTest.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#81 🔀 :: 정보 입력 - 외국어 정보 입력 페이지
  Projects/App/Sources/Application/NeedleGenerated.swift
  Projects/Feature/InputInformationFeature/Sources/DI/InputInformationComponent.swift
  Projects/Feature/InputInformationFeature/Sources/Intent/InputInformationIntent.swift
  Projects/Feature/InputInformationFeature/Sources/Intent/InputInformationIntentProtocol.swift
  Projects/Feature/InputInformationFeature/Sources/Scene/InputInformationView.swift
  Projects/Feature/InputLanguageInfoFeature/Interface/InputLanguageDelegate.swift
  Projects/Feature/InputLanguageInfoFeature/Interface/InputLanguageInfoBuildable.swift
  Projects/Feature/InputLanguageInfoFeature/Sources/DI/InputLanguageInfoComponent.swift
  Projects/Feature/InputLanguageInfoFeature/Sources/Intent/InputLanguageInfoIntent.swift
  Projects/Feature/InputLanguageInfoFeature/Sources/Intent/InputLanguageInfoIntentProtocol.swift
  Projects/Feature/InputLanguageInfoFeature/Sources/Model/InputLanguageInfoModel.swift
  Projects/Feature/InputLanguageInfoFeature/Sources/Model/InputLanguageInfoModelProtocol.swift
  Projects/Feature/InputLanguageInfoFeature/Sources/Model/LanguageInputModel.swift
  Projects/Feature/InputLanguageInfoFeature/Sources/Scene/InputLanguageInfoView.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#82 🔀 :: 정보 입력 - 프로필 정보 입력 페이지의 타이틀 오타
  Projects/Feature/InputProfileInfoFeature/Sources/Scene/InputProfileInfoView.swift
Labels: 3️⃣ Priority: Low, ⚡️ Simple

#83 🔀 :: Student API 제작
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/Dependency+Target.swift
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/ModulePaths.swift
  Projects/App/Project.swift
  Projects/App/Sources/Application/DI/AppComponent.swift
  Projects/App/Sources/Application/NeedleGenerated.swift
  Projects/Domain/StudentDomain/Demo/Resources/LaunchScreen.storyboard
  Projects/Domain/StudentDomain/Demo/Sources/DemoView.swift
  Projects/Domain/StudentDomain/Demo/Sources/DesignSystemDemoApp.swift
  Projects/Domain/StudentDomain/Interface/DI/StudentDomainBuildable.swift
  Projects/Domain/StudentDomain/Interface/DTO/Request/StudentRequestDTO.swift
  Projects/Domain/StudentDomain/Interface/DataSource/RemoteStudentDataSource.swift
  Projects/Domain/StudentDomain/Interface/Enums/FormOfEmployment.swift
  Projects/Domain/StudentDomain/Interface/Enums/MilitaryService.swift
  Projects/Domain/StudentDomain/Interface/Error/StudentDomainError.swift
  Projects/Domain/StudentDomain/Interface/Repository/StudentRepository.swift
  Projects/Domain/StudentDomain/Interface/UseCase/InputInformationUseCase.swift
  Projects/Domain/StudentDomain/Project.swift
  Projects/Domain/StudentDomain/Sources/DI/StudentDomainComponent.swift
  Projects/Domain/StudentDomain/Sources/DataSource/RemoteStudentDataSourceImpl.swift
  Projects/Domain/StudentDomain/Sources/Endpoint/StudentEndpoint.swift
  Projects/Domain/StudentDomain/Sources/Repository/StudentRepositoryImpl.swift
  Projects/Domain/StudentDomain/Sources/UseCase/InputInformationUseCaseImpl.swift
  Projects/Domain/StudentDomain/Testing/Testing.swift
  Projects/Domain/StudentDomain/Tests/Test.swift
Labels: 0️⃣ Priority: Critical, ⚙ Setting, ✨ Feature

#86 🔀 :: 근무 조건 페이지 희망 지역 복수입력으로 변경
  Projects/Feature/InputCertificateInfoFeature/Sources/Model/InputCertificateInfoModel.swift
  Projects/Feature/InputCertificateInfoFeature/Sources/Scene/InputCertificateInfoView.swift
  Projects/Feature/InputLanguageInfoFeature/Sources/Model/InputLanguageInfoModel.swift
  Projects/Feature/InputLanguageInfoFeature/Sources/Scene/InputLanguageInfoView.swift
  Projects/Feature/InputWorkInfoFeature/Sources/Intent/InputWorkInfoIntent.swift
  Projects/Feature/InputWorkInfoFeature/Sources/Intent/InputWorkInfoIntentProtocol.swift
  Projects/Feature/InputWorkInfoFeature/Sources/Model/InputWorkInfoModel.swift
  Projects/Feature/InputWorkInfoFeature/Sources/Model/InputWorkInfoModelProtocol.swift
  Projects/Feature/InputWorkInfoFeature/Sources/Scene/InputWorkInfoView.swift
Labels: 2️⃣ Priority: Medium, ✨ Feature

#90 🔀 :: Validator 모듈 밑작업
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/Dependency+Target.swift
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/ModulePaths.swift
  Projects/App/Sources/Application/NeedleGenerated.swift
  Projects/Feature/BaseFeature/Project.swift
  Projects/Shared/Validator/Project.swift
  Projects/Shared/Validator/Sources/EmailValidator.swift
  Projects/Shared/Validator/Sources/RegexValidator.swift
  Projects/Shared/Validator/Sources/StringSizeValidator.swift
  Projects/Shared/Validator/Sources/URLValidator.swift
  Projects/Shared/Validator/Sources/Validator.swift
  Projects/Shared/Validator/Tests/EmailValidatorTests.swift
  Projects/Shared/Validator/Tests/RegexValidatorTests.swift
  Projects/Shared/Validator/Tests/StringSizeValidatorTests.swift
  Projects/Shared/Validator/Tests/URLValidatorTests.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#95 🔀 :: 화면 클릭 시 키보드 dismiss 처리
  Projects/Shared/ViewUtil/Sources/Extensions/View+hideKeyboard.swift
Labels: 1️⃣ Priority: High, ⚡️ Simple

#96 🔀 :: 프로필 정보 입력 페이지 분야 선택 Placeholder 변경
  Projects/Feature/InputProfileInfoFeature/Sources/Scene/InputProfileInfoView.swift
Labels: 0️⃣ Priority: Critical, ⚡️ Simple

#37 🔀 :: DesignSystem SMSSelectionControls 제작
  Projects/Core/DesignSystem/Demo/Sources/DemoView.swift
  Projects/Core/DesignSystem/Sources/SelectionControls/SMSSelectionControls.swift
Labels: 1️⃣ Priority: High, ⚙ Setting

#97 🔀 :: 정보 입력 - 프로필 정보 입력 검사
  Projects/Core/DesignSystem/Sources/TextField/SMSTextField.swift
  Projects/Feature/InputInformationFeature/Sources/Intent/InputInformationIntent.swift
  Projects/Feature/InputInformationFeature/Sources/Model/InputInformationModel.swift
  Projects/Feature/InputInformationFeature/Sources/Model/InputInformationModelProtocol.swift
  Projects/Feature/InputInformationFeature/Sources/Scene/View/InputInformationPageWrapView.swift
  Projects/Feature/InputProfileInfoFeature/Interface/InputProfileDelegate.swift
  Projects/Feature/InputProfileInfoFeature/Sources/Intent/InputProfileInfoIntent.swift
  Projects/Feature/InputProfileInfoFeature/Sources/Intent/InputProfileInfoIntentProtocol.swift
  Projects/Feature/InputProfileInfoFeature/Sources/Model/InputProfileInfoModel.swift
  Projects/Feature/InputProfileInfoFeature/Sources/Model/InputProfileInfoModelProtocol.swift
  Projects/Feature/InputProfileInfoFeature/Sources/Scene/InputProfileInfoView.swift
  Projects/Feature/InputProfileInfoFeature/Tests/InputProfileInfoFeatureTest.swift
  Projects/Shared/Validator/Sources/RegexValidator.swift
  Projects/Shared/Validator/Sources/URLValidator.swift
  Projects/Shared/ViewUtil/Sources/Extensions/View+buttonWrapper.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#99 🔀 :: 정보 입력 - 학교 생활 정보 입력 검사
  Projects/Feature/InputInformationFeature/Sources/Intent/InputInformationIntent.swift
  Projects/Feature/InputInformationFeature/Sources/Model/InputInformationModel.swift
  Projects/Feature/InputInformationFeature/Sources/Model/InputInformationModelProtocol.swift
  Projects/Feature/InputSchoolLifeInfoFeature/Interface/InputSchoolLifeDelegate.swift
  Projects/Feature/InputSchoolLifeInfoFeature/Sources/Intent/InputSchoolLifeInfoIntent.swift
  Projects/Feature/InputSchoolLifeInfoFeature/Sources/Intent/InputSchoolLifeInfoIntentProtocol.swift
  Projects/Feature/InputSchoolLifeInfoFeature/Sources/Model/InputSchoolLifeInfoModel.swift
  Projects/Feature/InputSchoolLifeInfoFeature/Sources/Model/InputSchoolLifeInfoModelProtocol.swift
  Projects/Feature/InputSchoolLifeInfoFeature/Sources/Scene/InputSchoolLifeInfoView.swift
  Projects/Feature/InputSchoolLifeInfoFeature/Tests/InputSchoolLifeInfoFeatureTest.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#107 🔀 :: SMSEndpoint에 Domain 지정 추가
  Projects/Domain/AuthDomain/Sources/Endpoint/AuthEndpoint.swift
  Projects/Domain/BaseDomain/Sources/Base/SMSDomain.swift
  Projects/Domain/BaseDomain/Sources/Base/SMSEndpoint.swift
  Projects/Domain/BaseDomain/Sources/RefreshEndpoint/RefreshEndpoint.swift
  Projects/Domain/StudentDomain/Sources/Endpoint/StudentEndpoint.swift
Labels: 0️⃣ Priority: Critical, ♻️ Refactor

#108 🔀 :: 정보 입력 - 근무 조건 페이지 정보 검사 및 입력 전달
  Projects/Domain/StudentDomain/Interface/Enums/FormOfEmployment.swift
  Projects/Domain/StudentDomain/Interface/Enums/MilitaryService.swift
  Projects/Feature/InputInformationFeature/Sources/Intent/InputInformationIntent.swift
  Projects/Feature/InputInformationFeature/Sources/Model/InputInformationModel.swift
  Projects/Feature/InputInformationFeature/Sources/Model/InputInformationModelProtocol.swift
  Projects/Feature/InputSchoolLifeInfoFeature/Sources/Intent/InputSchoolLifeInfoIntent.swift
  Projects/Feature/InputSchoolLifeInfoFeature/Sources/Model/InputSchoolLifeInfoModel.swift
  Projects/Feature/InputSchoolLifeInfoFeature/Sources/Model/InputSchoolLifeInfoModelProtocol.swift
  Projects/Feature/InputSchoolLifeInfoFeature/Sources/Scene/InputSchoolLifeInfoView.swift
  Projects/Feature/InputSchoolLifeInfoFeature/Tests/InputSchoolLifeInfoFeatureTest.swift
  Projects/Feature/InputWorkInfoFeature/Interface/InputWorkDelegate.swift
  Projects/Feature/InputWorkInfoFeature/Project.swift
  Projects/Feature/InputWorkInfoFeature/Sources/Intent/InputWorkInfoIntent.swift
  Projects/Feature/InputWorkInfoFeature/Sources/Intent/InputWorkInfoIntentProtocol.swift
  Projects/Feature/InputWorkInfoFeature/Sources/Model/InputWorkInfoModel.swift
  Projects/Feature/InputWorkInfoFeature/Sources/Model/InputWorkInfoModelProtocol.swift
  Projects/Feature/InputWorkInfoFeature/Sources/Scene/InputWorkInfoView.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#111 🔀 :: 정보 입력 - 병역 정보 검사 및 입력 전달
  Projects/Domain/StudentDomain/Interface/DTO/Request/StudentRequestDTO.swift
  Projects/Domain/StudentDomain/Interface/Enums/MilitaryService.swift
  Projects/Domain/StudentDomain/Interface/Enums/MilitaryServiceType.swift
  Projects/Feature/InputInformationFeature/Sources/Intent/InputInformationIntent.swift
  Projects/Feature/InputInformationFeature/Sources/Model/InputInformationModel.swift
  Projects/Feature/InputInformationFeature/Sources/Model/InputInformationModelProtocol.swift
  Projects/Feature/InputMilitaryInfoFeature/Interface/InputMilitaryDelegate.swift
  Projects/Feature/InputMilitaryInfoFeature/Project.swift
  Projects/Feature/InputMilitaryInfoFeature/Sources/Intent/InputMilitaryInfoIntent.swift
  Projects/Feature/InputMilitaryInfoFeature/Sources/Intent/InputMilitaryInfoIntentProtocol.swift
  Projects/Feature/InputMilitaryInfoFeature/Sources/Model/InputMilitaryInfoModel.swift
  Projects/Feature/InputMilitaryInfoFeature/Sources/Model/InputMilitaryInfoModelProtocol.swift
  Projects/Feature/InputMilitaryInfoFeature/Sources/Scene/InputMilitaryInfoView.swift
  Projects/Feature/InputMilitaryInfoFeature/Tests/InputMilitaryInfoFeatureTest.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#105 🔀 :: 전공 가져오기 API 제작
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/Dependency+Target.swift
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/ModulePaths.swift
  Projects/App/Project.swift
  Projects/App/Sources/Application/DI/AppComponent.swift
  Projects/App/Sources/Application/NeedleGenerated.swift
  Projects/Core/DesignSystem/Demo/Sources/DemoView.swift
  Projects/Domain/MajorDomain/Interface/DI/MajorDomainBuildable.swift
  Projects/Domain/MajorDomain/Interface/DataSource/RemoteMajorDataSource.swift
  Projects/Domain/MajorDomain/Interface/Error/MajorDomainError.swift
  Projects/Domain/MajorDomain/Interface/Repository/MajorRepository.swift
  Projects/Domain/MajorDomain/Interface/UseCase/FetchListUseCase.swift
  Projects/Domain/MajorDomain/Project.swift
  Projects/Domain/MajorDomain/Sources/DI/MajorComponent.swift
  Projects/Domain/MajorDomain/Sources/DTO/Response/MajorListResponseDTO.swift
  Projects/Domain/MajorDomain/Sources/DataSource/RemoteMajorDataSourceImpl.swift
  Projects/Domain/MajorDomain/Sources/Endpoint/MajorEndpoint.swift
  Projects/Domain/MajorDomain/Sources/Repository/MajorRepositoryImpl.swift
  Projects/Domain/MajorDomain/Sources/UseCase/FetchListUseCaseImpl.swift
  Projects/Domain/MajorDomain/Testing/Testing.swift
  Projects/Domain/MajorDomain/Tests/MajorDomainTest.swift
Labels: 0️⃣ Priority: Critical, ⚙ Setting

#116 🔀 :: 정보 입력 - 외국어 정보 입력 검사 및 정보 전달
  Projects/App/Sources/Application/NeedleGenerated.swift
  Projects/Feature/InputInformationFeature/Sources/Intent/InputInformationIntent.swift
  Projects/Feature/InputInformationFeature/Sources/Intent/InputInformationIntentProtocol.swift
  Projects/Feature/InputInformationFeature/Sources/Model/InputInformationModel.swift
  Projects/Feature/InputInformationFeature/Sources/Model/InputInformationModelProtocol.swift
  Projects/Feature/InputInformationFeature/Sources/Scene/InputInformationView.swift
  Projects/Feature/InputLanguageInfoFeature/Interface/InputLanguageDelegate.swift
  Projects/Feature/InputLanguageInfoFeature/Sources/Intent/InputLanguageInfoIntent.swift
  Projects/Feature/InputLanguageInfoFeature/Sources/Intent/InputLanguageInfoIntentProtocol.swift
  Projects/Feature/InputLanguageInfoFeature/Sources/Scene/InputLanguageInfoView.swift
  Projects/Feature/InputLanguageInfoFeature/Tests/InputLanguageInfoFeatureTest.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#120 🔀 :: ImageUpload API 제작
  Projects/App/Sources/Application/NeedleGenerated.swift
  Projects/Domain/FileDomain/Interface/DI/FileDomainBuildable.swift
  Projects/Domain/FileDomain/Interface/DataSource/RemoteFileDataSource.swift
  Projects/Domain/FileDomain/Interface/Error/FileDomainError.swift
  Projects/Domain/FileDomain/Interface/Repository/FileRepository.swift
  Projects/Domain/FileDomain/Interface/UseCase/DreamBookUploadUseCase.swift
  Projects/Domain/FileDomain/Interface/UseCase/ImageUploadUseCase.swift
  Projects/Domain/FileDomain/Sources/DI/FileDomainComponent.swift
  Projects/Domain/FileDomain/Sources/DTO/Response/ImageUploadResponseDTO.swift
  Projects/Domain/FileDomain/Sources/DataSource/RemoteFileDataSourceImpl.swift
  Projects/Domain/FileDomain/Sources/Endpoint/FileEndpoint.swift
  Projects/Domain/FileDomain/Sources/Repository/FileRepositoryImpl.swift
  Projects/Domain/FileDomain/Sources/UseCase/ImageUploadUseCaseImpl.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#123 🔀 :: 이미지 가져올 방법 선택 BottomSheet 제작
  Projects/App/Support/Info.plist
  Projects/Core/DesignSystem/Resources/Icon/Icons.xcassets/Photo.imageset/Contents.json
  Projects/Core/DesignSystem/Resources/Icon/Icons.xcassets/Photo.imageset/Image 1.svg
  Projects/Core/DesignSystem/Resources/Icon/Icons.xcassets/Photo.imageset/Image 2.svg
  Projects/Core/DesignSystem/Resources/Icon/Icons.xcassets/Photo.imageset/Image.svg
  Projects/Core/DesignSystem/Sources/Icon/SMSIcon.swift
  Projects/Feature/InputProfileInfoFeature/Sources/Intent/InputProfileInfoIntent.swift
  Projects/Feature/InputProfileInfoFeature/Sources/Intent/InputProfileInfoIntentProtocol.swift
  Projects/Feature/InputProfileInfoFeature/Sources/Model/InputProfileInfoModel.swift
  Projects/Feature/InputProfileInfoFeature/Sources/Model/InputProfileInfoModelProtocol.swift
  Projects/Feature/InputProfileInfoFeature/Sources/Scene/InputProfileInfoView.swift
Labels: 1️⃣ Priority: High, ✨ Feature

#121 🔀 :: 정보 기입 API 통신 로직 구현
  Projects/App/Sources/Application/NeedleGenerated.swift
  Projects/Domain/StudentDomain/Interface/DTO/Request/StudentRequestDTO.swift
  Projects/Feature/InputInformationFeature/Project.swift
  Projects/Feature/InputInformationFeature/Sources/DI/InputInformationComponent.swift
  Projects/Feature/InputInformationFeature/Sources/Intent/InputInformationIntent.swift
  Projects/Feature/InputInformationFeature/Sources/Model/InputInformationModel.swift
  Projects/Feature/InputInformationFeature/Sources/Model/InputInformationModelProtocol.swift
  Projects/Feature/InputInformationFeature/Sources/Scene/InputInformationView.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#129 🔀 :: Signin View 파일 위치 변환
  Projects/Feature/SigninFeature/Sources/Scene/View/GAuthButtonView.swift
Labels: 1️⃣ Priority: High, ⚡️ Simple

#128 🔀 :: 정보 입력 - 프로필, 학교 생활 정보 입력 버튼 Disabled 상태 추가
  Projects/Feature/InputProfileInfoFeature/Sources/Model/InputProfileInfoModel.swift
  Projects/Feature/InputProfileInfoFeature/Sources/Model/InputProfileInfoModelProtocol.swift
  Projects/Feature/InputProfileInfoFeature/Sources/Scene/InputProfileInfoView.swift
  Projects/Feature/InputSchoolLifeInfoFeature/Sources/Model/InputSchoolLifeInfoModel.swift
  Projects/Feature/InputSchoolLifeInfoFeature/Sources/Model/InputSchoolLifeInfoModelProtocol.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#125 🔀 :: Major Selector 만들기
  Projects/App/Sources/Application/NeedleGenerated.swift
  Projects/Core/DesignSystem/Sources/BottomSheet/SMSBottomSheet.swift
  Projects/Core/DesignSystem/Sources/CameraPicker/CameraPicker.swift
  Projects/Domain/MajorDomain/Testing/Testing.swift
  Projects/Domain/MajorDomain/Testing/UseCase/FetchMajorListUseCaseSpy.swift
  Projects/Feature/InputProfileInfoFeature/Project.swift
  Projects/Feature/InputProfileInfoFeature/Sources/DI/InputProfileInfoComponent.swift
  Projects/Feature/InputProfileInfoFeature/Sources/Intent/InputProfileInfoIntent.swift
  Projects/Feature/InputProfileInfoFeature/Sources/Intent/InputProfileInfoIntentProtocol.swift
  Projects/Feature/InputProfileInfoFeature/Sources/Model/InputProfileInfoModel.swift
  Projects/Feature/InputProfileInfoFeature/Sources/Model/InputProfileInfoModelProtocol.swift
  Projects/Feature/InputProfileInfoFeature/Sources/Scene/InputProfileInfoView.swift
  Projects/Feature/InputProfileInfoFeature/Sources/Scene/View/ImageMethodPickerView.swift
  Projects/Feature/InputProfileInfoFeature/Sources/Scene/View/ImageMethodRowView.swift
  Projects/Feature/InputProfileInfoFeature/Sources/Scene/View/MajorRowView.swift
  Projects/Feature/InputProfileInfoFeature/Tests/InputProfileInfoFeatureTest.swift
Labels: 1️⃣ Priority: High, ✨ Feature

#133 🔀 :: 프로필 입력 페이지 FocusField 처리
  Projects/App/Sources/Application/NeedleGenerated.swift
  Projects/Core/DesignSystem/Sources/TextField/SMSTextField.swift
  Projects/Feature/InputProfileInfoFeature/Sources/Model/InputProfileInfoModel.swift
  Projects/Feature/InputProfileInfoFeature/Sources/Scene/InputProfileInfoView.swift
  Projects/Feature/InputWorkInfoFeature/Sources/Model/InputWorkInfoModel.swift
  Projects/Feature/InputWorkInfoFeature/Sources/Scene/InputWorkInfoView.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#134 🔀 :: TextField의 에러가 활성화 될때 vmark의 위치가 이상해 지는 현상 해결
  Projects/Feature/InputProfileInfoFeature/Sources/Scene/InputProfileInfoView.swift
Labels: 2️⃣ Priority: Medium, 🐞 Bug

#138 🔀 :: SMS 앱 아이콘 추가
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/sms-appicon.png
Labels: 0️⃣ Priority: Critical, ⚙ Setting, 🌏 Deploy

#136 🔀 :: 로그인 성공 이후 화면 전환
  Projects/Feature/RootFeature/Sources/Intent/RootIntent.swift
  Projects/Feature/RootFeature/Sources/Intent/RootIntentProtocol.swift
  Projects/Feature/RootFeature/Sources/Scene/RootView.swift
  Projects/Feature/SigninFeature/Interface/SigninBuildable.swift
  Projects/Feature/SigninFeature/Interface/SigninDelegate.swift
  Projects/Feature/SigninFeature/Sources/DI/SigninComponent.swift
  Projects/Feature/SigninFeature/Sources/Intent/SigninIntent.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#139 🔀 :: SwiftLint RunScript에서 warning뜨는 현상 해결
  Tuist/ProjectDescriptionHelpers/Action+Template.swift
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#140 🔀 :: 정보 입력 페이지 중복 코드 개선
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/Dependency+Target.swift
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/ModulePaths.swift
  Projects/Core/DesignSystem/Sources/Separator/SMSSeparator.swift
  Projects/Feature/InputCertificateInfoFeature/Project.swift
  Projects/Feature/InputCertificateInfoFeature/Sources/Scene/InputCertificateInfoView.swift
  Projects/Feature/InputInformationBaseFeature/Project.swift
  Projects/Feature/InputInformationBaseFeature/Sources/InputInformationPageTitleView.swift
  Projects/Feature/InputLanguageInfoFeature/Project.swift
  Projects/Feature/InputLanguageInfoFeature/Sources/Scene/InputLanguageInfoView.swift
  Projects/Feature/InputMilitaryInfoFeature/Project.swift
  Projects/Feature/InputMilitaryInfoFeature/Sources/Scene/InputMilitaryInfoView.swift
  Projects/Feature/InputProfileInfoFeature/Project.swift
  Projects/Feature/InputProfileInfoFeature/Sources/Scene/InputProfileInfoView.swift
  Projects/Feature/InputSchoolLifeInfoFeature/Project.swift
  Projects/Feature/InputSchoolLifeInfoFeature/Sources/Scene/InputSchoolLifeInfoView.swift
  Projects/Feature/InputWorkInfoFeature/Project.swift
  Projects/Feature/InputWorkInfoFeature/Sources/Scene/InputWorkInfoView.swift
Labels: 3️⃣ Priority: Low, ♻️ Refactor

#141 🔀 :: AuthDomainError를 API명세서와 동일하게 수정합니다
  Projects/Domain/AuthDomain/Interface/Error/AuthDomainError.swift
  Projects/Domain/AuthDomain/Sources/Endpoint/AuthEndpoint.swift
  Projects/Domain/AuthDomain/Testing/DataSource/RemoteAuthDataSourceSpy.swift
  Projects/Domain/AuthDomain/Testing/Repository/AuthRepositorySpy.swift
  Projects/Domain/AuthDomain/Testing/UseCase/LoginUseCaseSpy.swift
  Projects/Domain/AuthDomain/Tests/Repository/AuthRepositorySpec.swift
  Projects/Domain/AuthDomain/Tests/UseCase/LoginUseCaseSpec.swift
Labels: 1️⃣ Priority: High, ♻️ Refactor

#142 🔀 :: TextField에 텍스트 입력 시 xmark와 겹쳐지던 현상 해결
  Projects/Core/DesignSystem/Demo/Sources/DemoView.swift
  Projects/Core/DesignSystem/Sources/TextField/SMSTextField.swift
Labels: 1️⃣ Priority: High, ♻️ Refactor

#144 🔀 :: GAuth 환경 변수 이름 오타 수정
  Projects/App/Support/Info.plist
  Projects/Feature/SigninFeature/Sources/Scene/View/GAuthButtonView.swift
Labels: 0️⃣ Priority: Critical, ⚡️ Simple

#148 🔀 :: Emdpoint 버전 업그레이드
  Tuist/Dependencies.swift
Labels: 0️⃣ Priority: Critical, ⚙ Setting

#38 🔀 :: DesignSystem SMSDialog 제작
  Projects/App/Sources/Application/NeedleGenerated.swift
  Projects/Core/DesignSystem/Demo/Sources/DemoView.swift
  Projects/Core/DesignSystem/Sources/Dialog/SMSAlertButtonType.swift
  Projects/Core/DesignSystem/Sources/Dialog/SMSDialog.swift
Labels: 1️⃣ Priority: High, ⚙ Setting

#153 🔀 :: 디자인 시스템 - Checkbox 작업
  Projects/App/Sources/Application/NeedleGenerated.swift
  Projects/Core/DesignSystem/Demo/Sources/DemoView.swift
  Projects/Core/DesignSystem/Resources/Icon/Icons.xcassets/Checkmark.imageset/Contents.json
  Projects/Core/DesignSystem/Resources/Icon/Icons.xcassets/Checkmark.imageset/checkmark 1.svg
  Projects/Core/DesignSystem/Resources/Icon/Icons.xcassets/Checkmark.imageset/checkmark 2.svg
  Projects/Core/DesignSystem/Resources/Icon/Icons.xcassets/Checkmark.imageset/checkmark.svg
  Projects/Core/DesignSystem/Sources/Button/CTA/CTAButton.swift
  Projects/Core/DesignSystem/Sources/Button/Fill/FillButton.swift
  Projects/Core/DesignSystem/Sources/Chip/SMSChip.swift
  Projects/Core/DesignSystem/Sources/Dialog/SMSDialog.swift
  Projects/Core/DesignSystem/Sources/Icon/SMSIcon.swift
  Projects/Core/DesignSystem/Sources/SelectionControls/Checkbox/SMSCheckbox.swift
  Projects/Core/DesignSystem/Sources/SelectionControls/PressedSelectionControlStyle.swift
  Projects/Core/DesignSystem/Sources/SelectionControls/RadioButton/SMSRadioButton.swift
  Projects/Core/DesignSystem/Sources/SelectionControls/SMSSelectionControls.swift
  Projects/Core/DesignSystem/Sources/Text/SMSText.swift
  Projects/Core/DesignSystem/Sources/TextField/SMSTextField.swift
  Projects/Feature/InputMilitaryInfoFeature/Sources/Scene/InputMilitaryInfoView.swift
  Projects/Feature/InputProfileInfoFeature/Sources/Scene/View/MajorRowView.swift
  Projects/Feature/InputWorkInfoFeature/Sources/Scene/InputWorkInfoView.swift
  Projects/Shared/ViewUtil/Sources/Extensions/View+roundedStroke.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature
