Repository GSM-MSG/SMS-iOS, pull requests merged in 2023-09, with the labels that each got.

#270 🔀 :: [#269] 정보입력 직접입력 안되는 버그 수정
  Projects/App/Sources/Application/NeedleGenerated.swift
  Projects/Feature/MyPageFeature/Sources/Intent/MyPageIntent.swift
  Projects/Feature/MyPageFeature/Sources/Intent/MyPageIntentProtocol.swift
  Projects/Feature/MyPageFeature/Sources/Intent/MyPageProfileIntent.swift
  Projects/Feature/MyPageFeature/Sources/Model/MyPageModel.swift
  Projects/Feature/MyPageFeature/Sources/Model/MyPageModelProtocol.swift
  Projects/Feature/MyPageFeature/Sources/Scene/MyPageProfileView.swift
  Projects/Feature/MyPageFeature/Sources/Scene/MyPageView.swift
  Projects/Feature/StudentDetailFeature/Sources/Intent/StudentDetailIntent.swift
Labels: 1️⃣ Priority: High, 🐞 Bug

#274 🔀 :: [#273] Military 바텀 시트 버튼 누를 시 내려가게 하기
  Projects/Feature/InputMilitaryInfoFeature/Sources/Scene/InputMilitaryInfoView.swift
  Projects/Feature/MyPageFeature/Sources/Scene/MyPageView.swift
Labels: 2️⃣ Priority: Medium, ✨ Feature

#272 🔀 :: [#271] 필터, 수정 했을 시 새로 refresh
  Projects/Feature/MainFeature/Sources/Intent/MainIntent.swift
  Projects/Feature/MyPageFeature/Demo/Sources/AppDelegate.swift
  Projects/Feature/MyPageFeature/Interface/MyPageDelegate.swift
  Projects/Feature/MyPageFeature/Sources/Intent/MyPageIntent.swift
  Projects/Feature/MyPageFeature/Sources/Scene/MyPageView.swift
  Projects/Feature/RootFeature/Project.swift
  Projects/Feature/RootFeature/Sources/Intent/RootIntent.swift
Labels: 1️⃣ Priority: High, ✨ Feature

#276 🔀 :: WorkInfo 근무지역 한글자만 입력되는 이슈 해결
  Projects/Feature/InputWorkInfoFeature/Sources/Intent/InputWorkInfoIntent.swift
  Projects/Feature/MyPageFeature/Sources/Intent/MyPageWorkInfoIntent.swift
Labels: 1️⃣ Priority: High, 🐞 Bug

#280 🔀 :: [#279] 바텀시트 고치기 및 수상 date 옵셔널로 수정
  Projects/Feature/InputPrizeInfoFeature/Sources/Intent/InputPrizeInfoIntent.swift
  Projects/Feature/InputPrizeInfoFeature/Sources/Model/InputPrizeInfoModel.swift
  Projects/Feature/InputPrizeInfoFeature/Sources/Model/InputPrizeInfoModelProtocol.swift
  Projects/Feature/MyPageFeature/Sources/Scene/View/ImageMethodPickerView.swift
  Projects/Feature/MyPageFeature/Sources/Scene/View/ImageMethodRowView.swift
Labels: 1️⃣ Priority: High

#282 🔀 :: [#281] 프로젝트 focus 동시에 두개 되던 버그 고치기
  Projects/Feature/InputProjectInfoFeature/Sources/Scene/InputProjectInfoView.swift
  Projects/Feature/MyPageFeature/Sources/Scene/MyPageProjectView.swift
Labels: 1️⃣ Priority: High, ⚡️ Simple, ✨ Feature

#285 🔀 :: [#283] 마이페이지 prize 안 접히는 문제 해결
  Projects/Feature/MyPageFeature/Sources/Intent/MyPageIntent.swift
  Projects/Feature/MyPageFeature/Sources/Model/MyPagePrizeModel.swift
Labels: 1️⃣ Priority: High, ⚡️ Simple, 🐞 Bug

#288 🔀 :: [#284] Camera 권한 확인 추가
  Projects/App/Sources/Application/NeedleGenerated.swift
  Projects/Core/DesignSystem/Sources/CameraPicker/CameraPicker.swift
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#295 🔀 :: [#290] 짜잘한 버그 수정
  Projects/App/Sources/Application/NeedleGenerated.swift
  Projects/Feature/InputWorkInfoFeature/Sources/Model/InputWorkInfoModel.swift
  Projects/Feature/MyPageFeature/Sources/Intent/MyPageIntent.swift
  Projects/Feature/MyPageFeature/Sources/Intent/MyPageIntentProtocol.swift
  Projects/Feature/MyPageFeature/Sources/Model/MyPageModel.swift
  Projects/Feature/MyPageFeature/Sources/Model/MyPageWorkInfoModel.swift
  Projects/Feature/MyPageFeature/Sources/Scene/MyPageProjectView.swift
  Projects/Feature/MyPageFeature/Sources/Scene/MyPageSchoolLifeView.swift
  Projects/Feature/MyPageFeature/Sources/Scene/MyPageView.swift
  Projects/Feature/MyPageFeature/Sources/Scene/MyPageWorkInfoView.swift
  Projects/Feature/StudentDetailFeature/Sources/Scene/StudentDetailView.swift
  Projects/Feature/StudentDetailFeature/Sources/Scene/View/ProjectRowView.swift
  Projects/Shared/Validator/Sources/URLValidator.swift
Labels: 0️⃣ Priority: Critical, ♻️ Refactor, 🐞 Bug

#297 🔀 :: [#296] 기술스택 글자 수 30자 제한
  Projects/Feature/TechStackAppendFeature/Sources/Intent/TechStackAppendIntent.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature
