Repository GSM-MSG/SMS-iOS, pull requests merged in 2024-05, with the labels that each got.

#329 🔀 :: [#328] SMSTextField / xmark 아이콘 변경
  Projects/Core/DesignSystem/Demo/Sources/DemoView.swift
  Projects/Core/DesignSystem/Resources/Icon/Icons.xcassets/Xmark.imageset/Contents.json
  Projects/Core/DesignSystem/Resources/Icon/Icons.xcassets/Xmark.imageset/Xmark.svg
Labels: 3️⃣ Priority: Low

#333 🔀 :: [#332] DesignSystem / Chip
  Projects/Core/DesignSystem/Sources/Chip/SMSChip.swift
  Projects/Core/DesignSystem/Sources/Chip/SMSChipButtonStyle.swift
Labels: 0️⃣ Priority: Critical

#327 🔀 :: [#326] DesignSystem / SMSSegmentedControl
  Projects/Core/DesignSystem/Sources/SegmentedControl/SMSSegmentedControl.swift
Labels: 0️⃣ Priority: Critical

#337 🔀 :: [#336] SMSSegmentedControl 외부에서 selected option을 제어 가능하게 변경
  Projects/Core/DesignSystem/Sources/SegmentedControl/SMSSegmentedControl.swift
Labels: 0️⃣ Priority: Critical, ♻️ Refactor

#331 🔀 :: [#330] DesignSystem / FileField
  Projects/Core/DesignSystem/Resources/Icon/Icons.xcassets/File.imageset/Contents.json
  Projects/Core/DesignSystem/Resources/Icon/Icons.xcassets/File.imageset/file.svg
  Projects/Core/DesignSystem/Sources/File/FileField.swift
  Projects/Core/DesignSystem/Sources/Icon/SMSIcon.swift
  Projects/Core/DesignSystem/Sources/TextField/SMSTextEditor.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature
