Repository GSM-MSG/SMS-iOS, pull requests merged in 2024-02, with the labels that each got.

#316 🔀 :: [#315] 선생님 정보입력 페이지 UI
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/Dependency+Target.swift
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/ModulePaths.swift
  Projects/App/Project.swift
  Projects/App/Sources/Application/NeedleGenerated.swift
  Projects/Feature/InputTeacherInfoFeature/Demo/Resources/LaunchScreen.storyboard
  Projects/Feature/InputTeacherInfoFeature/Demo/Sources/AppDelegate.swift
  Projects/Feature/InputTeacherInfoFeature/Interface/InputTeacherDelegate.swift
  Projects/Feature/InputTeacherInfoFeature/Interface/InputTeacherInfoBuildable.swift
  Projects/Feature/InputTeacherInfoFeature/Project.swift
  Projects/Feature/InputTeacherInfoFeature/Sources/DI/InputTeacherInfoComponent.swift
  Projects/Feature/InputTeacherInfoFeature/Sources/Intent/InputTeacherInfoIntent.swift
  Projects/Feature/InputTeacherInfoFeature/Sources/Intent/InputTeacherInfoIntentProtocol.swift
  Projects/Feature/InputTeacherInfoFeature/Sources/Model/InputTeacherInfoModel.swift
  Projects/Feature/InputTeacherInfoFeature/Sources/Model/InputTeacherInfoModelProtocol.swift
  Projects/Feature/InputTeacherInfoFeature/Sources/Scene/InputTeacherInfoView.swift
  Projects/Feature/InputTeacherInfoFeature/Sources/Source.swift
  Projects/Feature/InputTeacherInfoFeature/Tests/InputTeacherInfoFeatureTest.swift
Labels: 1️⃣ Priority: High, ✨ Feature, 🙋‍♂️ Question

#319 🔀 :: [#318] teacher 도메인 세팅
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/Dependency+Target.swift
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/ModulePaths.swift
  Projects/App/Project.swift
  Projects/Domain/BaseDomain/Sources/Base/SMSDomain.swift
  Projects/Domain/TeacherDomain/Interface/DI/TeacherDomainBuildable.swift
  Projects/Domain/TeacherDomain/Interface/DateSource/RemoteTeacherDataSource.swift
  Projects/Domain/TeacherDomain/Interface/Error/TeacherDomainError.swift
  Projects/Domain/TeacherDomain/Interface/Repository/TeacherRepository.swift
  Projects/Domain/TeacherDomain/Interface/UseCase/CommonSignupUseCase.swift
  Projects/Domain/TeacherDomain/Interface/UseCase/DeputyPrincipalSignupUseCase.swift
  Projects/Domain/TeacherDomain/Interface/UseCase/DirectorSignupUseCase.swift
  Projects/Domain/TeacherDomain/Interface/UseCase/HomeRoomSignupUseCase.swift
  Projects/Domain/TeacherDomain/Interface/UseCase/PrincipalSignupUseCase.swift
  Projects/Domain/TeacherDomain/Project.swift
  Projects/Domain/TeacherDomain/Sources/DI/TeacherDomainComponent.swift
  Projects/Domain/TeacherDomain/Sources/DataSource/RemoteTeacherDataSourceImpl.swift
  Projects/Domain/TeacherDomain/Sources/Endpoint/TeacherEndPoint.swift
  Projects/Domain/TeacherDomain/Sources/Repository/TeacherRepositoryImpl.swift
  Projects/Domain/TeacherDomain/Sources/Source.swift
  Projects/Domain/TeacherDomain/Sources/UseCase/CommonSignupUseCaseImpl.swift
  Projects/Domain/TeacherDomain/Sources/UseCase/DeputyPrincipalSignupUseCaseImpl.swift
  Projects/Domain/TeacherDomain/Sources/UseCase/DirectorSignupUseCaseImpl.swift
  Projects/Domain/TeacherDomain/Sources/UseCase/HomeRoomSignupUseCaseImpl.swift
  Projects/Domain/TeacherDomain/Sources/UseCase/PrincipalSignupUseCaseImpl.swift
  Projects/Domain/TeacherDomain/Testing/Testing.swift
  Projects/Domain/TeacherDomain/Tests/TeacherDomainTest.swift
Labels: 1️⃣ Priority: High, ⚙ Setting, ✨ Feature

#320 🔀 :: [#317] 인증제 입력 페이지 퍼블리싱
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/Dependency+Target.swift
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/ModulePaths.swift
  Projects/App/Project.swift
  Projects/App/Sources/Application/NeedleGenerated.swift
  Projects/Core/DesignSystem/Sources/TextField/SMSTextEditor.swift
  Projects/Feature/InputAuthenticationFeature/Demo/Resources/LaunchScreen.storyboard
  Projects/Feature/InputAuthenticationFeature/Demo/Sources/AppDelegate.swift
  Projects/Feature/InputAuthenticationFeature/Interface/InputAuthenticationBuildable.swift
  Projects/Feature/InputAuthenticationFeature/Interface/InputAuthenticationDelegate.swift
  Projects/Feature/InputAuthenticationFeature/Project.swift
  Projects/Feature/InputAuthenticationFeature/Sources/DI/InputAuthenticationComponent.swift
  Projects/Feature/InputAuthenticationFeature/Sources/Intent/InputAuthenticationIntent.swift
  Projects/Feature/InputAuthenticationFeature/Sources/Intent/InputAuthenticationProtocol.swift
  Projects/Feature/InputAuthenticationFeature/Sources/Model/InputAuthenticationModel.swift
  Projects/Feature/InputAuthenticationFeature/Sources/Model/InputAuthenticationModelProtocol.swift
  Projects/Feature/InputAuthenticationFeature/Sources/Scene/InputAuthenticationView.swift
  Projects/Feature/InputAuthenticationFeature/Sources/Source.swift
  Projects/Feature/InputAuthenticationFeature/Tests/InputAuthenticationFeatureTest.swift
Labels: 1️⃣ Priority: High, ✨ Feature

#324 🔀 :: [#323] 오류 해결
  Projects/App/Sources/Application/NeedleGenerated.swift
  Projects/Feature/InputAuthenticationFeature/Project.swift
Labels: 0️⃣ Priority: Critical, 🐞 Bug
